twmb/franz-go

pkg/kgo/broker.go
pkg/kgo/client.go
pkg/kgo/config.go
pkg/kgo/consumer.go
pkg/kgo/consumer_direct.go
pkg/kgo/consumer_group.go
pkg/kgo/errors.go
pkg/kgo/metadata.go
pkg/kgo/produce_request_test.go
pkg/kgo/sink.go
pkg/kgo/source.go
pkg/kgo/topics_and_partitions.go

This is a very large commit that aims to make a lot of things simpler to
reason about in the consumer code, and then includes a few other
bugfixes bundled in that I noticed along the way.
Before this, the consumer used a bunch of sequence numbers to track
changes across assignments / etc. These sequence numbers were then used
to knife out stale partitions / ignore in-progress work that was
completing for stale partitions, while still accepting the non-stale
results.
This sequence number tracking and partition knifing was actually really
complicated and difficult to reason about, and I was never fully
confident in it. I knew there was some bug somewhere, and getting it to
work in the first place had me tracking down some really complicated
bugs to begin with.
This mostly rewrites the …

rewrite the consumer & source code; other bug fixes

---

examples/transactions/main.go
examples/transactions/transactional_consumer.go
examples/transactions/transactional_producer.go

Hi @twmb! I'm implementing a new producer with this library since it seems to have great support for producing messages in transactions and I need exactly-once semantics. I ended up crafting a couple of examples to test things out and figured I might put them out there for the sake of consolidating some of the transaction documentation.
I know the other examples don't use a main package but I found it convenient to be able to run the example as-is so I left it in there. More than happy to make changes to that or any other part of this.
As a side note, if I'm doing anything wrong here I'd really appreciate any feedback or guidance here.
Example output (repeats every 10s):
```
produced message: batch 0 record 0
produced message: batch 0 record 1
produced message: batch 0 record 2
produced …
```

Add examples for transactional producer and consumer

---

pkg/kgo/client.go
pkg/kgo/compression.go
pkg/kgo/config.go
pkg/kgo/consumer.go
pkg/kgo/consumer_direct.go
pkg/kgo/consumer_group.go
pkg/kgo/errors.go
pkg/kgo/group_balancer.go
pkg/kgo/internal/sticky/graph.go
pkg/kgo/internal/sticky/sticky.go
pkg/kgo/metadata.go
pkg/kgo/producer.go
pkg/kgo/sink.go
pkg/kgo/source.go
pkg/kgo/topics_and_partitions.go
pkg/kgo/txn.go

See each individual commit; this contains a series of updates that touch metadata & the consumer & mostly the producer, and by the end we are now able to cancel produce records without breaking sequence numbers.
Also throws in a few sticky perf increases for fun.

General updates

---

docs/README.md

A small improvement to the formatting of the docs README.md.
I believe this is the desired layout based on the original markdown.

Improve formatting and fix a typo

---

examples/bench/compare/confluent-kafka-go/main.go
examples/bench/compare/sarama/main.go
examples/bench/compare/segment/main.go
examples/bench/main.go

`printRate()` is already called with `go printRate()` so remove another `go func() {}()` inside `printRate()` methods.

bench: fix double goroutine invoke for printRate()

---

pkg/kgo/config.go

I have found a slight inconsistency.
[fetch.max.wait.ms](https://kafka.apache.org/documentation/#consumerconfigs_fetch.max.wait.ms)

config: edit comment for FetchMaxWait (about Java setting)

---

pkg/kgo/config.go
pkg/kgo/consumer_group.go

One of the features preventing full adoption of `franz-go` in my application was the ability for consumer groups to swizzle offsets upon assignment of topics & partitions before consumption on those topics begins. In `confluent-kafka-go` this is illustrated via [this example](https://gist.github.com/edenhill/9dfc019b980a5eb3365c84524a1f12b0).
This PR offers a means via callback function (set with a GroupOpt) to intercept those assignments and change them before cursors are created.

Support delegation of offset management before consumer group topic consumption begins

---

pkg/kgo/config.go
pkg/kgo/txn.go

And lower the default from 100ms to 20ms in line with Java Kafka client

config: add producer option to configure transactions backoff duration

---

pkg/kadm/kadm.go

Just a quick fix to one of the kadm convenience representations
Tested with:
```go
dg, err := adm.DescribeGroups(context.Background(), group)
ts := dg.AssignedPartitions()
tl := ts.Sorted()
fmt.Println(tl[0].Topic)
fmt.Println(len(ts[tl[0].Topic]), len(tl[0].Partitions))
```
to see if partitions in the output TopicsList match those in the input TopicsSet
As a side note, I used librdkafka previously and recall seeing a 'top-par' type often. In kadm it is equivalent to the Partition Type and it can be a handy abstraction (not always). I wondered if some other kadm structs could embed Partition. Perhaps Offset, ListedOffset, DescribedLogDirPartition or DeleteRecordsResponse? I am happy to submit a suggestion, if it could be useful.

Fix kadm Sorted: TopicsSet -> TopicsList function

---

pkg/sr/config.go

Currently sr.URLs will prepend http:// onto urls with https:// addresses making it unusable with https based schema registries.

Fix sr.URLs handling of https

---

pkg/kgo/record_and_fetch.go

https://github.com/twmb/franz-go/issues/188#issuecomment-1208129136
Following pattern allocates a new slice under the hood. 
```
if len(fetches.Records()) == 0 {
return nil
}
```
Add helper methods which calculates total fetch size without allocation.
@twmb

Add Fetches.NumRecords(), Fetches.Empty()

---

pkg/kgo/record_and_fetch.go

Now returns 1 if bit 4 is set as stated in the comment

Record TimestampType functionality match comment

---

.github/workflows/lint-and-test.yml
pkg/kgo/config.go
pkg/kgo/group_test.go
pkg/kgo/helpers_test.go
pkg/kgo/producer.go
pkg/kgo/sink.go
pkg/kgo/source.go
pkg/kgo/txn.go
pkg/kgo/txn_test.go

This merges #223 and adds a bunch of preceding commits that should address test failures.

fixup kraft

---

pkg/kgo/sink.go

This patch is a follow-up to the 27880b4 which adds wrapping for sequence number while creating a new produce request.
This patch adds checking for possible integer overflow for the batch0Seq, which could be assigned to the recBuf.seq during the resetBatchDrainIdx() which could cause INVALID_RECORD error.
Fixes #226 
Signed-off-by: Ladislav Macoun <ladislavmacoun@gmail.com>

sink: fix sequence number overflow during draining

---

pkg/kgo/broker.go
pkg/kgo/client.go
pkg/kgo/config.go
pkg/kgo/consumer_group.go
pkg/kgo/errors.go
pkg/kgo/group_balancer.go
pkg/kgo/hooks.go
pkg/kgo/producer.go
pkg/kgo/sink.go
pkg/kgo/source.go
pkg/kgo/txn.go
pkg/kversion/kversion.go

kgo: work around KIP-345 and KIP-814 limitations if possible

---

.github/workflows/lint-and-test.yml

Hey @twmb, thanks for [the nudge](https://github.com/twmb/franz-go/pull/223#issuecomment-1284886598) :) I think this might just suffice.
Technically, the Docker command should look smth like this, I think (or at least that's what I've been cargo-culting for a while): `docker run --rm -p9092:9092 docker.vectorized.io/vectorized/redpanda:latest start --default-log-level=debug --smp 1 --reserve-memory 0M --overprovisioned --set redpanda.enable_transactions=true --kafka-addr 0.0.0.0:9092 --advertise-kafka-addr redpanda:9092`, but GitHub Actions [doesn't allow](https://stackoverflow.com/questions/60849745/how-can-i-run-a-command-in-github-action-service-containers) users to overwrite the Docker `CMD` yet, which is a very weird omission IMHO.

Fix Redpanda tests

---

.github/workflows/lint-and-test.yml
pkg/kgo/helpers_test.go
pkg/kgo/txn.go
pkg/kgo/txn_test.go

Turns out, redpanda does not like the EndBeginTxnUnsafe option. That's valid.

franz-go: test against redpanda

---

pkg/kgo/broker.go
pkg/kgo/client.go
pkg/kgo/record_formatter.go
pkg/kgo/txn.go

AWS is expiring credentials sooner than they say they will. Rather than being 3 seconds pessimistic, we will be between 3 and 5% pessimistic. At 12hrs, this has us re-authenticating ~30 minutes early.

franz-go: be more pessimistic about sasl lifetime timeout

---

.github/workflows/lint-and-test.yml
CHANGELOG.md

Also hopefully changes gh actions to not run tests on markdown file changes.

CHANGELOG: note incoming v1.9.1 release

---

generate/gen.go
pkg/kgo/broker.go
pkg/kgo/client.go
pkg/kmsg/generated.go

kgo: support forward & backward batch requests for FindCoordinator, OffsetFetch
Previously, the client was only forward compatible. Opting into batching
was at your own risk. We now default to batching and split to the old
single behavior as needed.
To support this, we have a new internal request version pinner. We
always pin to batched version, and if we get errBrokerTooOld, we split.
loadCoordinators is a good bit more complex now, and we basically delete
loadCoordinator.
This is a bit complicated to describe in a single commit message.
Closes #214

Support backcompat batching OffsetFetch, FindCoordinator

---

pkg/kgo/client_test.go
pkg/kgo/config.go
pkg/kgo/group_test.go
pkg/kgo/source.go

This adds three new APIs:
```go
func ConsumePreferringLagFn(fn PreferLagFn) ConsumerOpt
type PreferLagFn func(lag map[string]map[int32]int64, torderPrior []string, porderPrior map[string][]int32) ([]string, map[string][]int32)
func PreferLagAt(preferLagAt int64) PreferLagFn
```
These functions allow an end user to adjust the order of partitions that
are being fetched. Ideally, an end user will only need:
```go
kgo.ConsumePreferringLagFn(kgo.PreferLagAt(50))
```
But, PreferLagFn exists to allow for more advanced use cases.
Closes #222

kgo: add option to consume preferring laggy partitions

---

pkg/kgo/broker.go
pkg/kgo/consumer_group.go

Previously, if `lifetime - pessimism ` resulted in immediate SASL expiry, we would immediately re-SASL. We now remove the loop so that at least one request always goes through. The next request will see expiry and will again re-auth. We also drop our min pessimism from 2s to 1s.
Hopefully, this addresses #249.

kgo connection: always allow one request after SASL

---

pkg/sr/client.go
pkg/sr/go.mod
pkg/sr/serde.go
pkg/sr/serde_test.go

We pin to 1.19 so that we can pull in the new binary.AppendVarint, and in doing so, we convert to `any` for simplicity.
This adds support for a type to be indexes, which means the registry now supports protobuf definitions. We also add a few helper APIs.
```
func GenerateFn(func() any) SerdeOpt
func Index(...int) SerdeOpt
func (*Serde) SetDefaults(...SerdeOpt)
func (*Serde) DecodeNew([]byte) any
```
For #207

pkg/sr: pin to go1.19, convert to `any`, add support for indices

---

pkg/kadm/configs.go
pkg/kadm/groups.go
pkg/kadm/kadm.go
pkg/kadm/logdirs.go
pkg/kadm/misc.go
pkg/kadm/topics.go
pkg/kadm/txn.go
pkg/kgo/client.go

This will be released in a patch release for franz-go, and a minor release for kadm. The patch is because this always should have been supported and it's a minor internal niche behavior change. The minor is because in kadm, this is new API surface (but also in kadm, this includes a bugfix for DeleteRecords and two other really new APIs).

kgo/kadm: add support for WriteTxnMarkers

---

pkg/kadm/go.mod
pkg/kadm/go.sum

required for WriteTxnMarkers sharding

kadm: bump franz-go to 1.10.1

---

pkg/kgo/compression.go
pkg/kgo/compression_test.go
pkg/kgo/produce_request_test.go
pkg/kgo/sink.go

Rather than using int literals everywhere.
If we want to be a little more cautious, we could use explicit values for each `codecType` constant rather than just the values implied by `iota` - e.g. `codecGzip = 1`, etc.

Use a named enum for compression codecs

---

pkg/kgo/go115.go
pkg/kgo/go116.go

I believe that d5e80b38ca2be44853b776286c6f3c1c4704c403 reversed its build constraints. It looks like the intent is to use `error.Is` from Go 1.16 onward, and to use `strings.Contains` in Go 1.15.
However, per https://pkg.go.dev/cmd/go#hdr-Build_constraints , the go1.15 tag is set for all Go versions from Go 1.15 *onward*. That means that go115.go will be used in Go 1.16 and onward, and go116.go will only be used in Go 1.15.
This commit reverses that, so that go115.go (string.Contains) is used in Go 1.15 and go116.go (error.Is) is used in Go 1.16 onward.

Fix isNetClosedErr

---

pkg/kgo/client.go
pkg/kgo/config.go

It is possible we have a stale controller that no longer exists.

kgo: forget the controller if we do not know it

---

generate/definitions/04_leader_and_isr
generate/definitions/05_stop_replica
generate/definitions/06_update_metadata
generate/definitions/62_broker_registration
pkg/kmsg/generated.go

The protocols are changing a lot, so we will just remove these APIs until 3.4 is stabilized. They are broker to broker only, so they aren't that important anyway.

remove KIP-866 temporarily

---

generate/definitions/misc
pkg/kmsg/generated.go

This reverts commit b8459811983b3489830b0c7734723311a86e9238.
Just in case this changes before it is actually used -- we can just add the protocol when it is actually used in balancers themselves.

Revert "kmsg: commit new proto for KIP-881"

---

pkg/kgo/atomic_maybe_work.go
pkg/kgo/consumer_group.go
pkg/kgo/go118.go
pkg/kgo/go119.go
pkg/kgo/sink.go
pkg/kgo/txn.go

Instead of using our own atomicBool type, let's use the standard atomic.Bool type in versions of Go that contain it.

Use atomic.Bool in Go 1.19+

---

generate/definitions/23_offset_for_leader_epoch
generate/definitions/misc
pkg/kmsg/generated.go

This reverts commit a7c820032cc2255e2fa8414903cec6bfc2773535.
Kafka has changed the protocol within the release a few tiems; we'll wait until Kafka releases before we stabilize of our own protocol changes.

Revert "kmsg: commit new ConsumerMemberMetadata for KIP-792"

---

pkg/kadm/acls.go
pkg/kadm/go.mod
pkg/kadm/kadm.go
pkg/kadm/kadm_test.go

This will make it _much_ easier to get the one response a user is interested in.
Requires go1.19

kadm: bump to go1.19, add First{,E} and Any{,E} helpers

---

pkg/kgo/group_test.go
pkg/kgo/helpers_test.go
pkg/kgo/sink.go
pkg/kgo/source.go

adjustPreferringLag adds back topics and partitions that the user did not specify. For partitions specifically, we reuse a partition map for all topics rather than create potentially dozens of partition maps.
Previously, the code did not clear out the partition map entirely before moving onto the next topic. If a second topic had fewer partitions than a first topic, then we would add back fake partitions into our fetch, and when we went to build a fetch request, we would panic because the consumer offset pointer to use for the fake partition didn't exist.
We now properly clear the map entirely between topics.
Additionally, this fixes a bit of the previous behavior w.r.t. ordering: we documented that any unchanged ordering was preserved -- i.e. if you only wanted one partition at the …

pkg/kgo: bugfix ConsumePreferringLagFn

---

pkg/kgo/source.go

Previously, if a hook implemented both HookFetchRecordBuffered and HookFetchRecordUnbuffered, then HookFetchRecordUnbuffered would never be called. The type switch in this logic would always match the buffered case and never call unbuffered.
Reorganizing the conditionals a little bit ensures that the correct hook is always called.

kgo: patch HookFetchRecordUnbuffered

---

.github/workflows/lint-and-test.yml
pkg/kgo/client.go
pkg/kgo/client_test.go

Internally, OffsetFetchRequest is sharded, but only on old brokers. We
first try not sharding. To have this one-or-the-other behavior, we wrap
the request with an internal pinned type before issuing it. Before we
return the response shards to the user, we remove any pin wrapping.
The offset fetch sharder accidentally did not return a pinned req in
cases that were known to be failures (i.e. were actually not going to be
issued). This wasn't caught in testing because the only time this really
happens is when:
* the FindCoordinator request outright fails
* the broker's coordinator is not yet loaded
The latter case happens for a brief window when using groups for the
first time in a new cluster.
Rather than always return a pinned req, we instead check if the request
actually is pinned. This …

kgo.Client: avoid panic in OffsetFetchRequest when coordinator is not loaded

---

examples/requesting/request_metadata.go
examples/sasl/aws_msk_iam/main.go
go.mod
go.sum
pkg/kgo/broker.go
pkg/kgo/client.go
pkg/kgo/client_test.go
pkg/kgo/config.go
pkg/kgo/consumer.go
pkg/kgo/consumer_group.go
pkg/kgo/group_balancer.go
pkg/kgo/group_balancer_test.go
pkg/kgo/helpers_test.go
pkg/kgo/internal/sticky/help_test.go
pkg/kgo/internal/sticky/sticky.go
pkg/kgo/produce_request_test.go
pkg/kgo/producer.go
pkg/kgo/sink.go
pkg/kgo/source.go
pkg/kgo/txn.go
pkg/kversion/kversion.go

Required to fix kmsg.Record.TimestampDelta being an int32 instead of an int64.

franz-go: bump kmsg to v2

---

pkg/kgo/config.go
pkg/kgo/consumer.go
pkg/kgo/consumer_direct.go
pkg/kgo/sink.go

* This previously did not work for the direct consumer
* We now allow this work work for clients that do not consume anything to begin with
* We now allow a consumer to join a group with no topic interests, so that the end-user can add interests later

pkg/kgo: patch AddConsumeTopics

---

CHANGELOG.md
examples/requesting/request_metadata.go
examples/sasl/aws_msk_iam/main.go
go.mod
go.sum
pkg/kbin/primitives.go
pkg/kbin/primitives_test.go
pkg/kgo/broker.go
pkg/kgo/client.go
pkg/kgo/client_test.go
pkg/kgo/config.go
pkg/kgo/consumer.go
pkg/kgo/consumer_group.go
pkg/kgo/group_balancer.go
pkg/kgo/group_balancer_test.go
pkg/kgo/helpers_test.go
pkg/kgo/internal/sticky/help_test.go
pkg/kgo/internal/sticky/sticky.go
pkg/kgo/produce_request_test.go
pkg/kgo/producer.go
pkg/kgo/record_and_fetch.go
pkg/kgo/sink.go
pkg/kgo/source.go
pkg/kgo/txn.go
pkg/kversion/kversion.go

v1.11.4 is retraced, and kmsg v2 we do not talk about.

v1.11.5: support 64 bit timestamp deltas in a backcompat manner

---

pkg/kgo/consumer.go
pkg/kgo/consumer_direct_test.go
pkg/kgo/source.go

UnknownTopicID is now returned frequently on Kafka 3.4, and it looks due to topic state not being synced immediately on all brokers. This was causing TestIssue337 to fail due to an unexpected error in the fetch responses.
Now, we just strip all retryable errors.
We also improve the test a bit.

kgo: always strip retryable errors when consuming

---

pkg/kgo/consumer.go
pkg/kgo/consumer_direct_test.go

The keepFilter kept the topic being loaded since the prior function worked on a per-partition basis. If we invalidate the whole topic, we will not re-load it. Particularly, this showed up as a panic because if tps is empty, we return an empty consumer session.

consumer: take 2 on fixing potential panic from PurgeTopicsFromClient

---

generate/definitions/23_offset_for_leader_epoch
generate/definitions/misc
pkg/kmsg/generated.go

For #272, we need to tag the kmsg protocol first.
This was originally merged, but for fear of Kafka changing the protocol again before release, this is waiting until the next Kafka release.

kmsg: commit new ConsumerMemberMetadata for KIP-792

---

generate/definitions/misc
pkg/kmsg/generated.go

This should only be merged once a Kafka release happens that uses the new protocol.

generate/kmsg: support KIP-881

---

examples/goroutine_per_partition_consuming/autocommit_marks/main.go
pkg/kgo/consumer_group.go

Hello,
When using a goroutine per partition with autocommit marks like in the provided example, the committed offsets are not the ones marked but the ones polled. This is because we issue a commit of uncommitted offsets on revoke [here](https://github.com/twmb/franz-go/blob/9d4480e85ca28b8cff03f78594acc3259b1d839e/examples/goroutine_per_partition_consuming/autocommit_marks/main.go#L78), uncommitted being `Uncommitted offsets are always updated on calls to PollFetches.`. 
Since we are consuming multiple polls (thanks to the [bufferred channel](https://github.com/twmb/franz-go/blob/9d4480e85ca28b8cff03f78594acc3259b1d839e/examples/goroutine_per_partition_consuming/autocommit_marks/main.go#L68)) and marking them asynchronously, if processing fails or is stopped, the uncommitted offsets are …

add CommitMarkedOffsets when using a custom onRevoked and AutoCommitMarks

---

README.md
pkg/kgo/broker.go
pkg/kgo/client.go
pkg/kgo/consumer.go

This allows an end user to update seed brokers, which can be valuable in long lived clients if the original set of seeds has completely rotated and no longer exist.
This satisfies KIP-899, allowing the client to "rebootstrap".
Closes #316.

kgo.Client: add UpdateSeedBrokers(...string) error

---

pkg/kgo/record_and_fetch.go

I was just reading the docs and saw what I think is a typo: DefailtProduceTopic -> DefaultProduceTopic

pkg/kgo: fix DefailtProduceTopic typo

---

pkg/kgo/source.go

See the embedded comment.
Some test presumably will need to be updated to tolerate unknown_topic_id failures in CI, since 3.4+ returns this for a brief period of time right after a topic is created.
Closes #357.

consumer: return UnknownTopicID even though it is retryable 

---

pkg/kgo/internal/sticky/help_test.go
pkg/kgo/internal/sticky/sticky.go

Drops allocs and CPU for pre-existing members a bit.
```
name                            old time/op    new time/op    delta
Large-12                          3.22ms ±13%    3.29ms ±15%     ~     (p=0.579 n=10+10)
LargeWithExisting-12              6.99ms ± 8%    6.96ms ±10%     ~     (p=0.684 n=10+10)
LargeImbalanced-12                4.00ms ± 6%    4.00ms ±16%     ~     (p=0.579 n=10+10)
LargeWithExistingImbalanced-12    7.13ms ± 4%    7.16ms ± 8%     ~     (p=0.842 n=9+10)
Java/large-12                      157ms ± 2%     157ms ± 1%     ~     (p=1.000 n=10+10)
Java/large_imbalance-12            195ms ± 1%     199ms ± 5%     ~     (p=0.070 n=7+10)
Java/medium-12                    14.4ms ±20%    13.2ms ±15%     ~     (p=0.123 n=10+10)
Java/medium_imbalance-12          16.2ms ±21% …
```

sticky: decode userdata directly to avoid allocs

---

pkg/kfake/pid.go

If we have n records starting at m, then next record we expect to see after that should be n+m, not n+m+1.

Fencepost error in pushAndValidate

---

pkg/kfake/data.go
pkg/kfake/pid.go

A couple of small fixes:
Producer IDs should always be positive.
SearchOffset had an off-by-one error looking for the appropriate batch.

Fix producer ids; fix searchOffset

---

pkg/kgo/client_test.go
pkg/kgo/config.go
pkg/kgo/hooks.go

Since `kgo.Hook` is an empty interface `[]kgo.Hook` also satisfies the empty interface which leads to silent failures if not passed to `kgo.WithHooks` properly.
```golang
kgo.WithHooks(hooks...) // works
kgo.WithHooks(hooks) // nothing called
```
By doing a little extra work inside of the config validation these mistakes can be fixed up or be turned into runtime errors.
Closes #365.

check hooks and flatten slices of hooks

---

pkg/kgo/config.go
pkg/kgo/consumer.go
pkg/kgo/consumer_test.go
pkg/kgo/errors.go
pkg/kgo/helpers_test.go
pkg/kgo/metadata.go
pkg/kgo/source.go

FOR CONSUMING
This is a bit of an involved change for consuming, but overall, it works as it says on the tin.
FOR PRODUCING
We cannot have this same type of logic in the producer until produce requests support topic IDs. As well, the producer will be more complicated -- we will need to worry about ordering issues. So, we avoid doing anything for producers until the day comes.
For now, if a person recreates a topic, the person will most likely receive an OutOfOrderSequenceNumber error which looks like data loss.
If a person recreates a topic with fewer partitions, the partitions that were deleted now have all records failed on them (and are no longer considered writeable). The client will enter a state of permanently failing any record that is consistently hashed to the old partition, and …

kgo: add ConsumeRecreatedTopics option, for UNKNOWN_TOPIC_ID

---

pkg/kgo/producer.go
pkg/kgo/ring.go
pkg/kgo/sink.go

Not having a mutext lock & unlock caused a race where a transaction could
1 A call .pause to pause inflight
2 A that could load that there _are_ inflight requests 3 B inflight could finish and broadcast
4 A could then signal.Wait
The broadcast needed to trigger the wait in step 4, but the broadcast already happened because there was no lock.
Also removes some redundant returns that made some aspects of seqRingResp confusing.

kgo: bugfix transaction ending & beginning

---

examples/bench/compare/segment/main.go

This PR enables async commits to have a fair comparison with franz-go.

Fix for segment benchmark

---

pkg/kgo/consumer_direct_test.go
pkg/kgo/group_test.go

* Allow more time for the specific Issue tests
* Block rebalance in poll in the group tests, to avoid some rare duplicate processing

kgo tests: improve resilience

---

pkg/kfake/17_sasl_handshake.go
pkg/kfake/36_sasl_authenticate.go
pkg/kfake/50_describe_user_scram_credentials.go
pkg/kfake/51_alter_user_scram_credentials.go
pkg/kfake/NOTES
pkg/kfake/client_conn.go
pkg/kfake/cluster.go
pkg/kfake/config.go
pkg/kfake/go.mod
pkg/kfake/go.sum
pkg/kfake/main.go
pkg/kfake/sasl.go

Adds support for SASL requests; ACLs are lower priority though.

kfake sasl

---

pkg/kgo/consumer_group.go
pkg/kgo/group_test.go
pkg/kgo/txn_test.go

An extension of the prior patches -- LeaveGroup would quit join or sync, but the requests could be in flight and result in a final commit error. We need to wait for join&sync to finish before LeaveGroup succeeds.
This may block shutdown a bit.

group consuming: block LeaveGroup between join&sync

---

pkg/kgo/consumer.go
pkg/kgo/consumer_group.go
pkg/kgo/errors.go
pkg/kgo/group_test.go
pkg/kgo/helpers_test.go

It was possible to inject a context.Canceled error into a fetch by 1) assignPartitions stops a session
2) stopping a session cancels the context
3) canceling the context kills list/epoch inflight requests 4) error injected into a fetch response
5) user polls
6) stopping session finally strips any old fetches, but they were
already drained
We now avoid injecting a context.Canceled or context.DeadlineExceeded error. The other two possible injected errors are still relevant (data loss, group management problem).
This also:
* Adds debug logs for the prior join&sync vs. commit blocking behavior
* Adds an info log for injected errors
* Removes the internal offsetEpoch in favor of the exported EpochOffset, meaning existing debug logs now use the same order consistently
* Avoids deleting …

kgo: avoiding context.Canceled fetch from List/Epoch, improve testing&logs

---

.github/workflows/lint-and-test.yml
pkg/kgo/config.go
pkg/kgo/consumer_direct_test.go
pkg/kgo/helpers_test.go
pkg/kgo/metadata.go
pkg/kgo/source.go

While regex consuming, if a topic is deleted, we previously would forever continue to try fetching it. Now, if a topic is missing from a metadata response, we internally purge it.
We delete immediately with the assumption that once a topic is discovered, there is enough broker consensus that it will not be somehow accidentally missing on the next metadata update -- i.e., if a topic is missing, it's definitely deleted.
We only do this for regex consuming; for non-regex, the assumption is that if you specify topics to consume, you want them. If they are missing in a metadata response, we will continue to try to update the metadata even if the topic was deleted (and we will continue trying to fetch).
Closes #434

kgo: purge missing-from-meta topics while regex consuming

---

pkg/kadm/groups.go

When requesting many offsets without specifying any group, you'd expect zero responses. In that case the existing logic will yield true for AllFailed().

kadm: Fix AllFailed check in FetchOffsetsResponses

---

examples/hooks_and_logging/plugin_kotel/README.md
plugin/kotel/README.md
plugin/kotel/tracer.go

Building on PR #449, this PR follows the new messaging semantic by renaming the span operation for producing from 'send' to 'publish'.

kotel: Update span operation name from 'send' to 'publish'

---

pkg/kgo/client.go

There seems to be a race condition between `NewClient` and `Close`:
```
WARNING: DATA RACE
Read at 0x00c000783fb0 by goroutine 192:
runtime.mapiterinit()
/opt/hostedtoolcache/go/1.20.3/x64/src/runtime/map.go:815 +0x0
github.com/twmb/franz-go/pkg/kgo.(*Client).Close()
/home/runner/go/pkg/mod/github.com/twmb/franz-go@v1.13.3/pkg/kgo/client.go:951 +0x2ad
github.com/firebolt-analytics/services/pkg/gootstrap/gateways/kafka/kafkaconsumer.(*consumerImpl).Run.func1()
/home/runner/work/services/services/pkg/gootstrap/gateways/kafka/kafkaconsumer/consumer.go:104 +0x48
runtime.deferreturn()
/opt/hostedtoolcache/go/1.20.3/x64/src/runtime/panic.go:476 +0x32
github.com/firebolt-analytics/services/pkg/gootstrap/orchestrator.executeRunners.func1() …
```

kgo: fix race condition when closing the client

---

pkg/sr/api.go
pkg/sr/client.go

This adds the method `SchemaByID` which returns the whole `Schema` object for a given schema ID. In contrast to `SchemaTextByID` this one also returns the schema type to the caller.
It also changes how `SchemaTextByID` retrieves the schema text, by using the dedicated endpoint.

Add method for retrieving schema by ID

---

plugin/kotel/README.md
plugin/kotel/meter.go

We are considering switching to this awesome library in our company from sarama.
We are currently visualizing the throughput of consumers and producers by the number of records they consume and produce.
While the number of bytes gives a good indication of the throughput, I think that adding the number of messages in the default metrics would be a good addition, as together with the number of bytes would paint a more complete picture on the throughput.

kotel: add fetch_records.count and produce_records.count metrics

---

CHANGELOG.md
pkg/kgo/consumer.go

Poll previously would not return if only a fake fetch existed. For
example, if a user joined a group with an instance ID twice, the fenced
group member would never exit polling. We now check both the actual
ready sources and the fake sources in our poll condition loop.
Closes #479.

consumer: return from Poll if the only error is an injected fake

---

pkg/kgo/client.go
pkg/kgo/config.go

Opts into TLS without requiring a tls.Config

kgo: add DialTLS option

---

pkg/kadm/metadata.go

Previously, if a topic did not exist, then List would proceed happily and not include any partitions for it in the response. This is rarely if ever desired.

pkg/kadm: fail List<> methods if the topic being listed does not exist

---

pkg/kmsg/go.mod
plugin/klogrus/klogrus.go

v1 modules cannot retract a v2 module so it seems.
Also sneaks in a paranoia improvement to klogrus.

pkg/kmsg: do not retract v2, because it is impossible

---

pkg/sr/serde.go
pkg/sr/serde_test.go

This PR introduces `SerdeHeader` and defines `ConfluentHeader` as the default implementation. The behavior of `Serde` is the same, ~one small but important difference is a fixed bug in the encoding of the message index (see the second part of the PR description)~. The changes are mostly just a refactoring and extraction of the header encoding/decoding logic. It makes `Serde` a bit more flexible and future-proof, since the header format can be switched to a different implementation.
The motivation behind this change is to expose the logic for encoding/decoding the Confluent wire format header. Using this change the caller can now decode the ID manually if needed and fetch the schema from the schema registry.
```go
val, err := serde.DecodeNew(b)
if errors.Is(err, sr.ErrNotRegistered) {
id, …
```

Serde Header

---

pkg/kversion/kversion.go
pkg/kversion/kversion_test.go

Kafka v3.4 added envelope support for the Envelope request to the zk based broker, so I added that to kversion.
This made Envelope a required request for version detection ever since it was introduced -- v2.7 for raft -- and pinned version detection to "at least 2.7" for all cluster between 2.7 and 3.4.
We now ignore the envelope key when version guessing because ultimately other keys are differentiating enough. This allows version detection to now again correctly guess 2.7 through 3.4.
Tested against zk 3.1, 3.2, 3.5, as well as kraft 3.5 manually, and adds a unit test for the 3.1 versions.
Closes #536.

kversion: fix version detection for Kafka v2.7 through 3.4

---

pkg/sr/serde.go
pkg/sr/serde_test.go

This PR makes ConfluentHeader an exported type. It provides 3 useful methods when working with the Confluent wire format.
No changes in logic were made.

sr/serde: Export Confluent header.

---

pkg/sr/api.go
pkg/sr/client.go
pkg/sr/config.go
pkg/sr/enums.go
pkg/sr/params.go

With an HTTP API, the API can add query parameters periodically, any addition of which breaks a Go API where all query parameters are spelled out as method arguments.
Now, we have moved all query parameters into values in a context, and added a helper sr.WithParams to make it easy to build parameters. All APIs document which parameters they support. We also have global parameters on the client itself, if you always want to show deleted or something.
This also adds metadata and ruleset to the schema type, even though the validation of these is really only possible in the Java client (as documented via limitations).
Lastly, this adds support for a few missing APIs:
* SubjectsByID
* SchemaVersionsByID
* SubjectVersions
* SchemaTextByVersion
* AllSchemas
This breaks all CompatibilityLevel …

pkg/sr: update for new APIs and to be forward compatible

---

README.md

DeltaStream uses franz-go internally for all go microservices.

Add DeltaStream to README.md

---

pkg/kfake/cluster.go

Named returns were interfering with defer-err-cleanup. Although a Cluster is initialized, defer close on error was running on a nil Cluster because the return was nil, err.
We remove named returns so that the defer runs on the actual initialized Cluster variable.
Tested by modifying main.go with the code in the issue; panics before, does not panic after.
Closes #566.

kfake: do not panic if NewCluster fails

---

pkg/kgo/broker.go

Previously the check was against `maxSize`, which comes from the consumer configuration, so there's no point checking that to see if it is "HTTP".

Fix typo in parseReadSize

---

pkg/kgo/record_formatter.go
pkg/kgo/record_formatter_test.go

This also handles arbitrary spacing, so `{  "foo": true }` reads (and can then be produced as) `{"foo":true}`.

kgo.RecordReader: support %v{json} to read json values

---

pkg/kgo/client.go

For when you are using one client for both producing and consuming to the same topic.
Closes #543.

kgo: add PurgeTopicsFrom{Producing,Consuming}

---

pkg/kgo/client.go
pkg/kgo/config.go
pkg/kgo/consumer.go
pkg/kgo/group_test.go
pkg/kgo/producer.go
pkg/kgo/record_and_fetch.go
pkg/kgo/source.go

kgo: add MaxBufferedBytes, Buffered{Fetch,Produce}Bytes

---

pkg/kgo/client.go
pkg/kgo/consumer_group.go

This allows more control over timeouts when leaving a group or closing the client, and also gives more insight into group leave errors.
Closes #556.

kgo: add LeaveGroupContext

---

pkg/kgo/consumer_group.go
pkg/kgo/txn.go

Allows modifying TxnOffsetCommitRequest before it is issued -- particularly, to modify the metadata field.
Closes #559.

kgo: add PreCommitTxnFnContext

---

pkg/kgo/consumer_group.go
pkg/kgo/txn.go

This better mirrors TxnOffsetCommit, also in the same api call, and better mirrors how it's pretty universally Txn then Commit wherever you see it.
Also fixes the context in GroupTransactSession.End to actually be passed all the way to the commit function, and documents where it can be used.

kgo / changelog: last minute rename from CommitTxn to TxnCommit

---

pkg/sr/api.go

`omitempty` doesn't work for structs, as a result, the schema contains zero value of SchemaMetadata and SchemaRuleSet which fails to create the schema on redpanda.
https://pkg.go.dev/encoding/json#Marshal

pkg/sr: use ptr type for SchemaMetadata and SchemaRuleSet

---

pkg/kadm/groups.go

kadm: populate GroupMemberLag.{Topic,Partition} always

---

pkg/kadm/topics.go

This PR adds the ErrorMessage field to `CreatePartitionsResponse` and `DeleteTopicResponse`

kadm: include ErrorMessage in topic response

---

.github/workflows/lint-and-test.yml
.golangci.yml
generate/definitions/24_add_partitions_to_txn
pkg/kgo/consumer.go
pkg/kgo/helpers_test.go
pkg/kgo/ring.go
pkg/kgo/txn_test.go
pkg/kmsg/generated.go
pkg/sasl/aws/aws.go

Generates KIP-890 proto, at least what's added in Kafka 3.6

KIP-890 proto

---

go.mod
go.sum
pkg/kgo/client.go
pkg/kversion/kversion.go

Properly handles sharding AddPartitionsToTxn v4+, and we now detect Kafka 3.6 properly (although do not introduce a constant for it yet which would require a minor).

KIP-890 (part 1)

---

pkg/kgo/consumer.go
pkg/kgo/consumer_direct_test.go
pkg/kgo/source.go
pkg/kgo/topics_and_partitions.go

Issue #489 asked to stop returning data after a partition was paused -- the original implementation of pausing kept returning any data that was in flight or already buffered, and simply stopped fetching new data.
489 was dealt with by bumping the consumer session, which kills all in flight fetch requests. This was easy, but can cause a lot of connection churn if pausing and resuming a lot -- which is #585.
The new implementation allows fetches to complete, but strips data from fetches based on what is paused at the moment the fetches are being returned to the client. This does make polling paused fetches very slightly slower (a map lookup per partition), but there's only so much that's possible. If a partition is paused, we drop the data and do not advance the internal offset. If a …

kgo: do not rotate the consumer session when pausing topics/partitions

---

pkg/kgo/internal/sticky/sticky.go
pkg/kgo/internal/sticky/sticky_test.go

The sticky balancer currently strives for ultimate stickiness, with no regard to trying to balance topic partitions among members equally. When adding a member, it is often the case that an entire topic's partitions shifts to the other member, while the first member has the other topic.
By sorting by partition number before balancing, when the algorithm steals partitions from the end of an existing member to give to the new member, we ensure that we divvy up the topics equally to both members while still ensuring stickiness.
This is likely not perfect but it goes a long way.

sticky balancer: try for better topic distribution among members

---

pkg/kgo/consumer.go

Scenario is:
* Metadata update is actively running and has stopped an active session, returning all topicPartitions that were actively in list/epoch. These list/epoch loads are stored in reloadOffsets. Metadata grabs the session change mutex.
* Client.Close is now called, stores client.consumer.kill(true). The Close is blocked briefly because Close calls assignPartitions which tries to lock to stop the session. Close is now paused -- however, importantly, the consumer.kill atomic is set to true.
* Metadata tries to start a new session. startNewSession returns noConsumerSession because consumer.kill is now true.
* Metadata calls reloadOffsets.loadWithSession, which panics once the session tries to access the client variable c.
This panic can only happen if all of the following are true:
* …

kgo: avoid rare panic

---

pkg/kadm/acls.go
pkg/kadm/misc.go

The client calls SetVersion internally per request, so doing this concurrently leads to races.
Closes #597.

kadm: do not reuse ApiVersions in many concurrent requests

---

pkg/kgo/consumer_group.go
pkg/kgo/txn.go

This replaces #580, introducing one earlier commit that makes grabbing the group memberID and generation atomic (and thus, lock free / no concurrency issues).

kgo: allow PreTxnCommitFnContext to modify empty offsets

---

pkg/kgo/broker.go
pkg/kgo/client.go

Random iteration was removed with 1e5c11d1cd62e3df4f1dc307c8a849c830da4d04 We can reintroduce random iteration easily enough, while still keeping the behavior of try-a-seed-occasionally.
Closes #579.

kgo: reintroduce random broker iteration

---

plugin/kslog/README.md
plugin/kslog/go.mod
plugin/kslog/go.sum
plugin/kslog/kslog.go
plugin/kslog/kslog_test.go

This is a kgo.Logger wrapping [slog](https://pkg.go.dev/log/slog).
It will be really useful to us, as we're switching to it, so I though it might help others too.
slog is not experimental any more only from go 1.21, so whoever wants to use this plugin will need to use go version >= 1.21

feat(kslog): implemented kgo.Logger plugin with slog

---

pkg/kgo/consumer_group.go

kgo: no-op mark functions when not using AutoCommitMarks

---

.github/workflows/lint-and-test.yml
pkg/kgo/client.go

KIP-890 has been updated such that v3 must be used by clients. We will pin to v3 unless multiple transactions are being added, or unless any transaction is verify only.
Closes #609.

kgo: pin AddPartitionsToTxn to v3 when using one transaction

---

pkg/kgo/consumer.go
pkg/kgo/consumer_direct_test.go
pkg/kgo/source.go

Follow up from #585, there was a bug in the commit for it. If any topic
was paused, then all non-paused topics would be returned once, but they
would not be marked as fetchable after that.
I _think_ the non-fetchability would eventually be cleared on a metadata
update, _but_ the source would re-fetch from the old position again. The
only way the topic would advance would be if no topics were paused after
the metadata update.
However this is a bit confusing, and overall this patch is required.
This also patches a second bug in PollFetches with pausing: if a topic
has a paused partition, if the fetch response does NOT contain any
paused partitions, then the logic would actually strip the entire topic.
The pause tests have been strengthened a good bit -- all lines but one
are hit, and the …

kgo: be sure to use topics when other topics are paused

---

pkg/kgo/internal/sticky/go121.go
pkg/kgo/internal/sticky/goold.go
pkg/kgo/internal/sticky/sticky.go
pkg/kgo/internal/sticky/sticky_test.go

* Introduces separate functions for go 1.21+, allowing to eliminate unremoveable allocs from sort.Sort. To keep it simple, this simplifies <=1.20 a little bit, so that is **slightly** more inefficient.
* Improves new-partition assignment further -- ensure we always place unassigned partitions on the least consuming member.

sticky: further improvements

---

pkg/kgo/config.go

Fix typo in the `TransactionalID` documentation.

chore: fix typo

---

pkg/kgo/source.go

If we receive OOOR while fetching after a fetch was previously successful, something odd happened in the broker. Either what we were consuming was truncated underfoot, which is normal and expected (for very slow consumers), or data loss occurred without a leadership transfer. We will reset to the nearest offset after our prior consumed offset (by time!) because, well, that's what's most valid: we previously had a valid offset, and now it is invalid.
Closes #621.

consuming: reset to nearest if we receive OOOR while fetching

---

pkg/kgo/compression.go

optimisation: avoid ReadAll and use bytes buffer instead 

---

pkg/sr/api.go
pkg/sr/client.go
pkg/sr/params.go

While working with the schema registry client in `pkg/sr`, we started to receive "not found" HTTP errors seemingly out of nowhere while registering schemas with `CreateSchema()`.
After closer examination, I found that the culrpit was that the base URL for the schema registry had a trailing slash in some of our configurations. For example `http://localhost:18081/` instead of `http://localhost:18081`.
After further examination, I traced back the issue to this line:
https://github.com/twmb/franz-go/blob/c09dc92d2db141d00c9eeb8ea229f72869222ca3/pkg/sr/client.go#L103
Where it is evident that the complete request URL results in the form `http://localhost:18081//path/to/resource` (incorrect).
I observed that the "not found" errors happen in both, Confluent Schema Registry and Redpanda.
To …

pkg/sr: improve base URL and resource path joining

---

pkg/kfake/01_fetch.go
pkg/kfake/08_offset_commit.go
pkg/kfake/09_offset_fetch.go
pkg/kfake/11_join_group.go
pkg/kfake/12_heartbeat.go
pkg/kfake/13_leave_group.go
pkg/kfake/14_sync_group.go
pkg/kfake/15_describe_groups.go
pkg/kfake/16_list_groups.go
pkg/kfake/17_sasl_handshake.go
pkg/kfake/36_sasl_authenticate.go
pkg/kfake/42_delete_groups.go
pkg/kfake/47_offset_delete.go
pkg/kfake/client_conn.go
pkg/kfake/cluster.go
pkg/kfake/groups.go
pkg/kfake/sasl.go

This function allows you to sleep a function you are controlling until your wakeup function returns. The control function effectively yields to other requests. Note that since requests must be handled in order, you need to be a bit careful to not block other requests (unless you intentionally do that).
This basically does what it says on the tin. The behavior of everything else is unchanged -- you can KeepControl, you can return false to say it wasn't handled, etc.
The logic and control flow is a good bit ugly, but it works and is fairly documented and "well contained".
In working on this, I also found and fixed a bug that resulted in correllation errors when handling join&sync.
kgo group tests still work against kfake's "hidden" main.go, and I have tested SleepControl with/without …

kfake: add SleepControl

---

pkg/kfake/cluster.go
pkg/kfake/config.go
pkg/kfake/groups.go

* Sleeping was a bit limited because if two requests came in on the same connection, you could not really chain logic. Sleeping out of order allows you to at least run some logic to gate how requests behave with each other. It's not the most obvious, so it is not the default.
* Adds SleepOutOfOrder
* Adds CoordinatorFor so you can see which "broker" a coordinator request will go to
* Adds RehashCoordinators to change where requests are hashed to
The latter two allow you to loop rehashing until a coordinator for your key changes, if you want to force NotCoordinator requests.

kfake: add DropControl, SleepOutOfOrder, CoordinatorFor, RehashCoordinators

---

pkg/kgo/client.go

Some load testing in Redpanda showed a failure where consuming quit unexpectedly and unrecoverably.
The sequence of events is:
* if OffsetCommit is issued just before Heartbeat
* and the group needs to be loaded so FindCoordinator is triggered,
* and OffsetCommit happens again, canceling the prior commit's context
Then,
* FindCoordinator would cancel
* Heartbeat, which is waiting on the same load, would fail with context.Canceled
* This error is seen as a group leave error
* The group management logic would quit entirely.
Now, the context used for FindCoordinator is the client context, which is only closed on client close. This is also better anyway -- if two requests are waiting for the same coordinator load, we don't want the first request canceling to error the second request. If all …

kgo: do not cancel FindCoordinator if the parent context cancels

---

plugin/kotel/tracer.go

Add tombstone to tracer span attributes as defined in the otel conventions.
https://github.com/open-telemetry/opentelemetry-go/blob/v1.21.0/semconv/v1.18.0/trace.go#L2930-L2938

kotel/tracer: add tombstone attribute

---

plugin/klogrus/go.mod
plugin/klogrus/go.sum
plugin/klogrus/klogrus.go
plugin/klogrus/klogrus_test.go

Hello
We use some wrappers around `*logrus.Logger` and we don't want to write a wrapper each time we need to set the kafka logger
Instead, since most of the time we use `logrus.FieldLogger` with some extra methods, I decided to send this small contribution where we can use this _minimal_ interface
```go
// FieldLogger interface.
type FieldLogger interface {
logrus.FieldLogger
GetLevel() logrus.Level
}
```
The result is still compatible with logrus, but on steroids.
I was thinking in use the pure `logrus.FieldLogger` and store the log level (using two constructors, for instance) but I think we need to react to possible changes in the log level in runtime. This solution is cleaner
Also I add one test based on kslog plugin.
Enjoy

use interface instead *logrus.Logger in plugin klogrus

---

pkg/kfake/cluster.go

If we return while running a control function (which is expected to be fast), we may unlock a mutex that is currently unlocked and only relocked after the control function exits.
Notably, tryControl was panicking because a cluster was closed while a control function was running.

kfake: do not return early when running control functions if the cluster is closed

---

.github/workflows/lint-and-test.yml
bump-deps.sh
examples/bench/compare/sarama/go.mod
examples/bench/compare/sarama/go.sum
examples/bench/compare/sarama/main.go
go.mod
go.sum
pkg/kgo/internal/sticky/sticky.go
pkg/kgo/sink.go
pkg/kmsg/go.mod
pkg/sasl/kerberos/go.mod
plugin/kgmetrics/go.mod
plugin/klogr/go.mod
plugin/klogrus/go.mod
plugin/kprom/go.mod
plugin/kzap/go.mod
plugin/kzerolog/go.mod

For GH workflows, use latest stable

all: bump to go1.19

---

pkg/kgo/partitioner.go

Looks like `SaramaHasher` is not exactly compatible with sarama.
I switched from `segmentio/kafka-go` to `franz-go` and noticed that now my keys map to different partition (this is a no-go for my usecase).
I have created [a test to check key->partiton mapping consistency](https://github.com/C-Pro/partitioners/blob/master/partitioners_test.go) between sarama, segmentio and franz.
`kgo.StickyKeyPartitioner(SaramaCompatHasher(fnv32a))` returns different partition number.
Test output shows[ franz yields different partition numbers](https://github.com/C-Pro/partitioners/actions/runs/6956276996/job/18926787234).
So I added new `SaramaCompatHasher` that behaves exactly like sarama's and segmentio ones (uses int32 instead of int).
I opted to create a new instead of changing the existing …

sarama-compatible hasher

---

pkg/kgo/consumer.go
pkg/kgo/consumer_direct_test.go
pkg/kgo/metadata.go
pkg/kgo/topics_and_partitions.go

Unfortunately, it is very difficult to have SetOffsets set offsets for partitions that have not been consumed.
This added new topics, but the partitions would always start at 0.

SetOffsets patches revert

---

README.md

At [Sharechat](https://sharechat.com/about) we use `franz-go` quite heavily with both RedPanda and Kafka. It is the recommended client internally for golang.

Update `README.md` to add `Sharechat` as a user

---

pkg/sr/api.go

SubjectVersions calls pathSubjectWithVersion instead of pathSubject to build a path to retrieve all versions for a given subject.

sr SubjectVersions calls pathSubjectWithVersion

---

pkg/kfake/02_list_offsets.go

Closes #706 
This PR fixes the behaviour of how `kfake` handles `ListOffsets` API, when the request includes partition's timestamp. That is, the expected behaviour is to return the offset of the first batch _after_ the requested timestamp. As I pictured in #706, the current behaviour in the mainline is the opposite.
I didn't find a better way testing it, that to use the same example repo, I created to demo the problem. Refer to [this branch](https://github.com/narqo/test-kfake/tree/kfake-listoffsets-ts), where I replaced the `kfake` with my forked version.

kfake: fix handling ListOffsets when Timestamp is requested

---

pkg/kgo/consumer_group.go

Currently when using `AutoCommitMarks` option the only function available for marking is `MarkCommitRecords(rs ...*Record)`, this requires you to keep `Record`s in memory until they're marked (possibly for prolonged periods of time) unnecessarily since the marking itself doesn't really need anything other than the offsets.
I added a new function `MarkCommitOffsets` to do the same as `MarkCommitRecords` but accept a map of `EpochOffset`s instead, let me know what you think, thank you

pkg/kgo: allow marking using an offset

---

pkg/kgo/consumer.go
pkg/kgo/consumer_direct_test.go

Currently I am looking at multiple dynamic deployments of this library and I'm looking to implement checks prior to initialized polling which need to verify that the necessary topics have been assigned to the consumer client. 
Please advise if you require additional unit tests for the ConsumerGroup  path.

Added ability to retrieve current clients target topics

---

pkg/kgo/compression.go
pkg/kgo/record_formatter.go

Scrolling through code I found mysterious constants, looks like this should be `codecType`.
However, `codec` param is `byte` but `codecType` is `uint8` I don't think it's a problem. Changing function param will increase diff for no big reason.
Thanks for the `franz-go` BTW ;)

pkg/kgo: use codecType explicitly

---

pkg/kgo/consumer_group.go

If a consumer that can be cooperative but is currently eager revokes its assigned partitions as part of a rebalance it should also clear its tracking state between rebalances as it has revoked all of its partitions.
This was leading to some inconsistent behaviour when migrating from eager consumers to cooperative consumers following the migration instructions in [KIP-429](https://cwiki.apache.org/confluence/display/KAFKA/KIP-429%3A+Kafka+Consumer+Incremental+Rebalance+Protocol#KIP429:KafkaConsumerIncrementalRebalanceProtocol-Consumer).
Fixes #686

fix: clear lastAssigned when revoking eager consumer

---

pkg/kgo/broker.go

In this PR I'm proposing to add `req` field to 'read from broker errored' log. While investigating an incident, we had a case where such addition would have been helpful. I've used `req` as field name to keep it consistent with the same information logged in other places.
Fixes #719

Add request type to 'read from broker errored' log

---

pkg/kgo/config.go

I just realised that the `kgo.RequestTimeoutOverhead()` is the default timeout for most of the requests. I didn't understand it just reading the doc, as I thought it was always an overhead. I'm proposing a small rephrasing of the doc: does it make sense to you?

Clarify kgo.RequestTimeoutOverhead() documentation

---

pkg/kgo/client.go
pkg/kgo/metadata.go

In [Mimir](https://github.com/grafana/mimir), we have a process creating 1 `Client` (setting `MetadataMinAge` = MetadataMaxAge = 10s`) and then using it to do two things:
1. Consume a partition
2. Request `ListOffsets` every 1s
I noticed that such `Client` issues 2 `Metadata` requests every `MetadataMinAge` (remember that we set `MetadataMaxAge = MetadataMinAge`).
One request is due to the periodic Metadata refresh, and one is due to `ListOffsets` which need `Metadata` as well. `ListOffsets` request calls `Client.fetchMappedMetadata()` which caches the metadata for `MetadataMinAge`, so effectively leading to 2 `Metadata` requests every `MetadataMinAge`.
In this PR I'm proposing to optimistically cache the mapped metadata when cluster metadata is periodically refreshed.
- I'm not an expert …

Optimistically cache mapped metadata when cluster metadata is periodically refreshed

---

pkg/kgo/producer.go
pkg/kgo/sink.go

Currently if your linger is long and your max records small, it is possible to linger even if the client cannot buffer any more records.
Now, once max records or bytes is hit, we wakeup anything lingering and avoid entering the linger state again -- until we are no longer over max.
Closes #726.

kgo: avoid / wakeup lingering if we hit max bytes or max records

---

pkg/kgo/consumer_group.go

See the command #705 for more details.
Closes #705.

pkg/kgo: re-add fetch-canceled partitions AFTER the user callback

---

pkg/kadm/groups.go
pkg/kfake/08_offset_commit.go
pkg/kfake/groups.go
pkg/kgo/config.go
pkg/kgo/consumer.go
pkg/kgo/errors.go

This adds an Offset method that allows ConsumeResetOffset to exactly
mirror Kafka's auto.offset.reset = none
Closes #692

kgo.Offset: add AtCommitted()

---

pkg/kgo/consumer_direct_test.go

Fails locally without one of these two bumps, and it's not really important to diagnose which one is more important. My 2018? laptop is struggling here.

kgo: bump consumer_direct_test timeout, make non-parallel

---

pkg/sr/api.go
pkg/sr/client.go
pkg/sr/clientopt.go
pkg/sr/enums.go
pkg/sr/serde.go
pkg/sr/serde_test.go

* Renames Opt to ClientOpt
* Renames SerdeOpt to EncodingOpt
* Removes Serde.SetDefaults, in favor of the new (and more standard) NewSerde function
* Adds SerdeOpt, with the ability to set the header that is always used
* Adds top-level Encode/AppendEncode functions, to be used when you are dynamically encoding types and their ids / indices
This is #506 by @lovromazgon, rebased on master, squashed into one commit, with minor modifications

pkg/sr: touchups

---

pkg/sr/serde.go
pkg/sr/serde_test.go

This better mirrors the wire format -- the args seemed out of order if you knew the wire format.

pkg/sr: move SerdeHeader arg before id, index

---

.github/workflows/i386.yml
.github/workflows/lint-and-test.yml
pkg/kadm/groups.go
pkg/kgo/consumer.go

This adds one more round trip in the `Lag` function to request start offsets, but this improves the case when topics have segments deleted over time. We _could_ go through some detailed way of avoiding requests for partitions that have commits, but having the start offset is pretty valuable a lot of time time anyway -- and we keep the logic simpler.
Now,
* if a topic is assigned to a group,
* and a partition in that topic has no commits,
* and the log-start-offset for the partition is non-zero Lag will no longer show the entire partition as lagging from zero, but instead will show more accurately the log-end-offset - log-start-offset. If LEO == LSO, the lag is now zero, rather than LEO itself.
This also no longer says lag is negative if a commit is past the end of a partition; instead the …

kadm: improve Lag calculation to account for log-start-offset being non-zero

---

pkg/kadm/groups.go

Getting lag as nil, in case Lag method was called as `client.Lag(ctx)`, other methods of this library defaults to listing offsets and describing to all the groups/topics incase no group/topic is specified, Assuming the same behaviour for this method. 
e.g.
[Client.DescribeGroups](https://pkg.go.dev/github.com/twmb/franz-go/pkg/kadm#Client.DescribeGroups)
> DescribeGroups describes either all groups specified, or all groups in the cluster if none are specified.
[Client.ListTopics](https://pkg.go.dev/github.com/twmb/franz-go/pkg/kadm#Client.ListTopics)
> ListTopics issues a metadata request and returns TopicDetails. Specific topics to describe can be passed as additional arguments. If no topics are specified, all topics are requested. Internal topics are not returned unless specifically …

fix: client.Lag doesn't calculate lag for all consumergroups with client.Lag(ctx)

---

pkg/sr/serde.go
pkg/sr/serde_test.go

A small fix for a possible panic when a type is registered without a decode function. The test kinda hides this possibility, because `Serde` has a default `DecodeFn` option. This case is more likely to hit when `Serde` is instantiated without that option.
I removed the decode test case for schema ID 100, as it was the same as the one for ID 99, instead I added one with ID 101 which has a registered type, but no decode function.

SR: prevent panic when no decode function is registered

---

plugin/kotel/meter.go
plugin/kotel/meter_test.go

This PR follows the discussion in https://github.com/twmb/franz-go/issues/670.
I added a new struct field, `mergeConnectsMeter bool` that is manipulated by `WithMergedConnectsMeter()`, to control whether to use one or 2 metrics to track connection successes/errors.
By default is set to `false` to retain current behaviour.
When set to `true` it disables the creation of `messaging.kafka.connect_errors.count` metric and follows a different path in `Meter.OnBrokerConnect`. There is some repetition as I wanted to avoid additional allocations when manipulating otel attributes (unfortunately Attribute Sets don't offer a way to add/remove elements from the set).
I added tests for the previous and new behaviour.
Let me know what you think, happy to adjust based on your feedback and thank you for …

kotel: optionally only use messaging.kafka.connects.count for connection metrics

---

pkg/kfake/19_create_topics.go
pkg/kfake/data.go
pkg/kfake/groups.go

This isn't used at the moment; it gets in the way of using kfake to stub out behaviour that mocks custom cluster & topic config.

kfake: Drop topic configuration validation

---

README.md

We've been using `franz-go` at [EasyPost](https://github.com/EasyPost)

Update `README.md` to add `EasyPost` as a user

---

README.md

@twmb A huge thanks for this project!
We use it in Conduit, but also a few related but separate projects (our Kafka connector and our own schema registry). 
By the way, what do you think about removing Benthos, given that it's now Redpanda Connect?

Add Conduit to list of users

---

README.md

This simple PR updates the main README file to mention that `kafka-go` also works with Confluent Platform clusters.
We have been using this library for a while in production against Confluent Platform clusters with excellent results.
Therefore, make it clear that a user can expect this library to work well with CP as well.

README: `kafka-go` also works with Confluent Platform

---

pkg/kgo/sink.go

* Produce request created and about to be issued
* Metadata request resolves and removes the broker that was about to be sent to, updates leadership for the partition
* recBuf's `sink` field is updated
* The old sink then enters handleReqResp, then eventually handleRetryBatches
Previously,
* Failed partition triggers a metadata refresh and enters a failed state until the metadata refresh clears the failing state. Because a metadata refresh JUST happened, internally this causes a 5s wait by default
Now,
* Failed partition notices that it is actually NOW on a different broker than the broker that is handling the failure, and does not back off at all, and actually triggers potentially draining on the new sink once decInflight runs
Closes #746.

kgo sink: do not back off on certain edge case

---

pkg/kgo/compression.go
pkg/kgo/compression_test.go
pkg/kgo/logger.go
pkg/kgo/produce_request_test.go
pkg/kgo/sink.go

This MR resolves #623 by using a byte buffer in decompression instead of always creating a new one. It also replaces the custom `sliceWriter` with the standard `bytes.Buffer` everywhere.

refactor: replace sliceWriter with bytes.Buffer and use it in decompression 

---

pkg/kgo/compression.go
pkg/kgo/compression_test.go

fix setting lz4 compression levels

---

pkg/kgo/sink.go

When writing a record batch during a request, the batch mutex is locked. This guards against a concurrent failAllRecords, which can be triggered from a metadata update.
However, a boolean field that guarded against failing buffered records if it's not "safe" was not properly mutex guarded. Writing a request only locks the batch, not the owning recBuf, while checking to see if the batch could fail only locked the owning recBuf, not the batch.
This adds locking around the batch when checking if it can be failed, and adds a bool that, if true (due to load failures), ensures the batch is not written.
Closes #785.

kgo sink: fix read/write race for recBatch.canFailFromLoadErrs

---

.github/workflows/lint-and-test.yml
pkg/kgo/consumer_direct_test.go
pkg/kgo/produce_request_test.go
pkg/kgo/producer.go
pkg/kgo/sink.go

Copying from the issue,
"""
1) Produce() record A (100 bytes)
2) Produce() record B (50 bytes), waiting for buffer to free
3) Produce() record C (50 bytes), waiting for buffer to free
4) Record A is produced, finishRecordPromise() gets called, detects it was over the limit so publish 1 message to waitBuffer
5) Record B is unlocked, finishRecordPromise() gets called, does not detect it was over the limit (only 50 bytes), so record C is never unblocked and will wait indefinitely on waitBuffer
"""
The fix requires adding a lock while producing. This reuses the existing
lock on the `producer` type. This can lead to a few more spurious
wakeups in other functions that use this same mutex, but that's fine.
The prior algorithm counted anything to produce immediately into the
buffered records and …

kgo: fix deadlock in Produce when using MaxBufferedBytes 

---

pkg/kgo/errors.go
pkg/kgo/helpers_test.go
pkg/kgo/produce_request_test.go
pkg/kgo/producer.go
pkg/kgo/sink.go
pkg/kgo/source.go
pkg/kgo/txn.go

If a record's context is canceled, we now allow it to be failed in two
more locations:
* while the producer ID is loading -- we can actually now cancel the
producer ID loading request (which may also benefit people using
transactions that want to force quit the client)
* while a sink is backing off due to request failures
For people using transactions, canceling a context now allows you to
force quit in more areas, but the same caveat applies: your client will
likely end up in an invalid transactional state and be unable to
continue.
For #769.

kgo: allow record ctx cancelation to propagate a bit more

---

pkg/kadm/acls.go
pkg/kadm/configs.go
pkg/kadm/misc.go
pkg/kadm/partas.go
pkg/kadm/topics.go
pkg/kadm/txn.go

kadm: add ErrMessage to all types it was missing from

---

pkg/kadm/errors.go
pkg/kadm/errors_test.go

I have an use case where I need to check whether the request context was canceled / timed out. It would be helpful to me if we could make `ShardErrors` supporting `Unwrap()`, so that `errors.Is()` works on it.

Add ShardErrors.Unwrap() support

---

pkg/sr/api.go

The client missed the 'mode' key in the sr's PUT /mode body.
Documentation of the required body: https://docs.confluent.io/platform/current/schema-registry/develop/api.html#put--mode

sr: fix body of cl.SetMode

---

plugin/kprom/kprom.go

Earlier today I was wondering where exactly `write_bytes_total` and `read_bytes_total` are tracked, and I realized it counts the bytes we write and read from the wire.
What do you think if we clarify it in the metric description, including a specific mention with regards to compression?

Clarify bytes metrics description

---

pkg/sr/client.go
pkg/sr/clientopt.go

Add support for specifying bearer tokens in the schema registry client.

sr: add support for using bearer tokens in client

---

pkg/kfake/data.go

Setting the configs to `nil` causes it to panic later when trying to alter the topic configs, as [it only checks for entry in the map not being present, not for it not being nil](https://github.com/colega/franz-go/blob/f1cded5cc755374d6cac290c23da247ce5eb4e7a/pkg/kfake/data.go#L259-L261).

Don't set nil config when seeding topics in kfake cluster

---

pkg/kgo/record_and_fetch.go

Fix typo in Record.ProducerID doc comment.

---

.golangci.yml
generate/gen.go
pkg/kgo/produce_request_test.go
pkg/kgo/producer.go
pkg/kgo/record_and_fetch.go

Problem:
* Record A exceeds max, is on path to block
* Record B finishes concurrently
* Record A's context cancels
* Record A's goroutine waiting to be unblocked returns, leaves accounting mutex in locked state
* Record A's select statement chooses context-canceled case, trying to grab the accounting mutex lock
See #831 for more details.
Closes #831.

kgo: fix potential deadlock when reaching max buffered (records|bytes)

---

README.md
go.mod
go.sum
pkg/kerr/kerr.go
pkg/kgo/sink.go
pkg/kgo/txn.go
pkg/kversion/kversion.go

Not much changes in the client. End-users may now receive a new error that signals they can abort a transaction.

Kafka 3.8.0

---

pkg/kgo/txn.go

These two functions are basically required if you use the BlockRebalanceOnPoll function when initializing a GroupTransactSession, so, it seems worth it to promote these to direct APIs on GTS.
Closes #753.

kgo: add AllowRebalance and CloseAllowingRebalance to GroupTransactSession

---

pkg/kgo/errors.go

We want to test in a unit test the behaviour exposed in this question: https://github.com/twmb/franz-go/issues/784, where we rely on this error type. So we need to create this kind of error, with another wrapped one inside it in the tests.
Would this change be ok? The only side efect of it is that clients of the lib would be able to create it too.

kgo: export the wrapped error from ErrGroupSession

---

pkg/kgo/record_and_fetch.go
pkg/kgo/source.go

kgo: add TopicID to the FetchTopic type

---

pkg/sr/client.go

This adds the equivalent of `kgo.Client.Opts()` to the `sr.Client` implementation. The use-case would be if you want to initialize a Schema Registry client with an existing Schema Registry client, but say do something like change the credentials being used for authentication.

Add Opts method for sr.Client

---

pkg/kgo/config.go
pkg/kgo/metadata.go
pkg/kgo/sink.go

See embedded comment. This preceeds handling KIP-890.
Closes https://github.com/twmb/franz-go/issues/805.

kgo: ignore OOOSN where possible

---

pkg/kgo/consumer.go
pkg/kgo/consumer_direct.go
pkg/kgo/consumer_direct_test.go
pkg/kgo/consumer_group.go
pkg/kgo/metadata.go

The internal tps map is meant to be what we store topicPartitions in that we are candidates to be consumed. This is filtered in assignPartitions to only opt-in partitions that are actually being consumed.
It's not BAD if we store all topics in that map, but it's not the intent. The rest of the client worked fine even with extra topics in the map.
When regex consuming, the metadata function previously put all topics into the map always. Now, we move the regex evaluation logic -- duplicated in both the direct and group consumers -- into one function and use that for filtering within metadata.
This introduces a required sequence of filtering THEN finding assignments, which is fine / was the way things operated anyway.
Moving the filtering to metadata (only in the regex consuming logic) means …

kgo: do not add all topics to internal tps map when regex consuming

---

pkg/sr/go.mod

No real reason, no real reason not to. This also allows one commit after the top level franz tag.

pkg/sr: require go 1.22

---

pkg/sr/api.go

This would come in handy when someone is trying to migrate schemas between two Schema Registry instances and they wish to retain the original IDs to avoid schema ID translation when migrating Kafka messages.

Add `CreateSchemaWithIDAndVersion()` to the sr package

---

pkg/kadm/acls.go
pkg/kadm/acls_test.go

The authorized operations is an int32 bitfield
that represents ACL operations. This commit adds
a func that allows to decode the bitfield into
a slice of kmsg.ACLOperation values. This bitfield 
is used in the metadata, describe clusters and
describe groups API responses.
Fixes https://github.com/twmb/franz-go/issues/869

kadm: add func to decode AuthorizedOperations

---

pkg/kgo/producer.go
pkg/kgo/source.go

When a successfully produced batch is returned with an invalid base offset (-1) but no error, the records' internal offsets are being miscomputed from this value. An invalid offset is returned with a non-errored batch primarily in situations where a duplicate idempotent produce is detected, but the actual base offset cannot be provided. [Apache Kafka's producer client handles this](https://github.com/apache/kafka/blob/9d65ff8077fdfe1c2f1ec647fe5c0e6dac405622/clients/src/main/java/org/apache/kafka/clients/producer/RecordMetadata.java#L49C1-L50C1) by setting all record offsets to -1 if the batch's base offset is -1.
This patch makes this correction in the kgo producer callback logic, as well as in the `recordToRecord` function (though an invalid offset is probably impossible on the fetch …

Fix handling of invalid base offsets

---

pkg/kgo/producer.go

Previously, we would broadcast after every individual record finished in a batch. If we produced 5000 records concurrently but only allowed 1000 in flight, we would first send a few large batches, and then once they started finishing, we would:
* Finish a record
* Wake up a waiting record
* That record would race into producing
* The producing wouldn't linger even if we wanted to, because other records are blocked
* That record would be produced alone in one batch immediately
* Goto start
This forced unnecessary synchronization and caused things to produce slowly.
By doing one broadcast at the end of a batch, we actually give more "space" for the client to buffer before waking up everything waiting. The first goroutine awoken will still produce a small batch, _but_ we will reach a point …

kgo: broadcast batch finishes in one big blast

---

pkg/kgo/consumer_direct_test.go
pkg/kgo/hooks.go
pkg/kgo/source.go

Topics or partitions that were paused (in `takeNBuffered` specifically, which is used by PollRecords) did not have proper accounting for stripped (removed) topics or partitions. PollFetches does not have this problem because the logic is different -- we build a big fetch, call our accounting logic, and then remove the stripped topics & partitions. Instead in takeNBuffered, we skip topics and partitions as we build a fetch and then once the fetch is built, do the accounting.
The fix is to build a separate internal-only fetch of everything that was stripped and pass that to our accounting hooks.
Fixes #865.

kgo: fix accounting when topics/partitions are {,un}paused for PollRecords

---

pkg/kgo/errors.go
pkg/kgo/source.go

Kafka can return partial batches, so decompression errors are common. If I ask for at most 100 bytes, and the broker has two 60 byte batches, I will receive one valid 60 byte batch and then a partial 40 byte batch. The second partial batch will fail at decompressing. This is the reason I previously never returned decompression errors.
However, if a client truly does produce somewhat-valid compressed data that *some* decompressors can process, but *others* (Go's) cannot, then the first batch received could fail to decompress. The client would fail processing, return an empty batch, and try consuming at the same spot. The client would spin loop trying to consume and the end user would never be aware.
Now, if the first error received is a decompression error, we bubble it up to the end user. …

kgo: return decompression errors while consuming

---

pkg/kfake/01_fetch.go
pkg/kfake/cluster.go
pkg/kfake/data.go
pkg/kfake/go.mod
pkg/kfake/go.sum
pkg/kfake/issues_test.go
pkg/kfake/topic_partition.go

Adds APIs:
```
func (c *Cluster) LeaderFor(topic string, partition int32) int32
func (c *Cluster) SetFollowers(topic string, partition int32, followers []int32)
func (c *Cluster) TopicInfo(topic string) *TopicInfo
func (c *Cluster) PartitionInfo(topic string, partition int32) *PartitionInfo
func (c *Cluster) PartitionInfos(topic string) []*PartitionInfo
```
as well as two info structs.
These APIs and structs are used in a new test to exercise an edge
condition of follower fetching.
Todo followup is to move the test to a different directory, but that can
wait -- the "patten" established here is to write the test with a local
replace directive, ensure it works, merge the fix to franz-go, then bump
the dep here and actually push the test. Not the best pattern, but also
one that requires …

kfake: add test for #885, add new APIs

---

.golangci.yml
generate/gen.go

Note: You can use `golangci-lint config verify` to check if the `.golangci.yml` config matches the published schema.
- `tenv` has been deprecated in favour of `usetesting`
- `allow-leading-space` has been removed from `nolintlint`: https://github.com/golangci/golangci-lint/issues/3063
- `revive` doesn't have `error-code` `warning-code` as config options (see https://golangci-lint.run/usage/linters/#revive). There's some discussion https://github.com/mgechev/revive/issues/241 about adding `set_exit_status` to `revive`, but it's not exposed via `golangci-lint`

Fix linter errors

---

pkg/kgo/client.go

Mention that closing kgo Client will not send leave group request if static membership is being used.

docs: Document `Close` behavior when static membership is being used

---

.gitignore
pkg/kgo/consumer.go

I discovered a "bug" in the code responsible for handling the cancellation of a fetch request. Fortunately, it doesn’t seem to cause any immediate issues (if I’ve correctly understood the relationship between `manageFetchConcurrency` and `fetchLoop`). However I think it’s better to fix it now to prevent potential problems in the future when changes are made.
In this snippet, instead of deleting the `i`-th element, the last element is being removed:
```go
_ = append(wantFetch[i:], wantFetch[i+1:]...)
wantFetch = wantFetch[:len(wantFetch)-1]
```
I also attempted to write a test to cover this case, but it would require a significant redesign of `manageFetchConcurrency` so I’ve set this idea aside.

kgo: fix cancellation of a fetch in manageFetchConcurrency

---

pkg/kgo/logger.go

Bug | BasicLogger Panics When `len(keyvals)` is 1

---

pkg/kgo/sink.go

kgo: allow outstanding produce requests to be context canceled if the user disables idempotency

---

pkg/kgo/client.go
pkg/kgo/group_balancer.go
pkg/kgo/metadata.go

This can be used to reduce the number of metadata requests issued. As
followup, kadm should almost globally use this function.
Closes #800.

kgo: add Client.RequestCachedMetadata

---

examples/produce_with_ctx/README.md
examples/produce_with_ctx/go.mod
examples/produce_with_ctx/go.sum
examples/produce_with_ctx/main.go

This small example demonstrates a per message context with a timeout.
We _do_ expect franz-go kgo.Client to fully support context deadlines.
Clarifying: https://github.com/twmb/franz-go/issues/953

Produce with ctx

---

.github/workflows/lint-and-test.yml
.golangci.yml
pkg/kfake/cluster.go
pkg/kgo/client.go
pkg/kgo/compression.go
pkg/kgo/compression_test.go
pkg/kgo/config.go
pkg/kgo/consumer_direct_test.go
pkg/kgo/consumer_group.go
pkg/kgo/group_test.go
pkg/kgo/helpers_test.go
pkg/kgo/hooks.go
pkg/kgo/pools.go
pkg/kgo/produce_request_test.go
pkg/kgo/producer.go
pkg/kgo/record_and_fetch.go
pkg/kgo/record_formatter.go
pkg/kgo/sink.go
pkg/kgo/source.go
pkg/kgo/txn_test.go

* Exports the internal Compressor and Decompressor
* Adds WithCompressor and WithDecompressor options to allow end-user overrides
* Improves # of allocs when reading fetch responses by performing slab allocations
* Exports the function that processes fetch response partitions, allowing end-users to manually process fetch responses
* Adds a WithPools option and exposes three pools a user can provide to reuse memory while processing fetch responses
* Adds a DisableFetchCRCValidation consumer option, for if you really need this escape hatch (for #909)

kgo: allow compressor & decompressors to be entirely user driven; allow users to inject memory pools

---

pkg/kgo/client.go
pkg/kgo/config.go

Adds `ctx` field to allow custom contexts to be used by the client
For example, it allows the custom `onAssigned` func, added using `OnPartitionsAssigned` opt, to access a custom context and any propagated value inside (like tracers)

kgo: add ctx field to client cfg

---

pkg/kgo/producer.go
pkg/kgo/sink.go

Previously, if our tries was equal to the max retries, we would not retry. Instead, we should try again -- the number of tries is one less than the number of retries. We tried once, we retried 0 times.
Now, when we try twice, we have retried once, and we can fail properly. This also means that failing once will cause a metadata reload, rather than immediately failing the record and doing nothing.
This also switches freezing a batch to a dedicated bool field rather than relying on a secondary effect of counting how many times a batch has been tried. This allows us to move accounting of when a batch is actually tried to where it is actually being written, avoiding double counting of tries if the batch actually ends up not being sent after being selected to be sent (due to add partitions to …

kgo: fix off-by-one with retries accounting

---

pkg/kgo/group_test.go
pkg/kgo/helpers_test.go
pkg/kgo/producer.go
pkg/kgo/sink.go
pkg/kgo/txn_test.go

What this adds:
* After EndTxn, we send ListTransactions to verify the transaction has actually completed
* If the transaction hangs for 10s, we log and set internally to reinitialize the producer ID.
* We log a lot
Some logging changes will be kept; the ListTransactions verification will be deleted, as well as the hard-resetting of the producerID.

kgo: minor improvements while attempting to work around a Kafka hanging transaction bug

---

pkg/kgo/client.go
pkg/kgo/config.go
pkg/kgo/source.go

The cluster may occasionally pick a new preferred replica. If the client is consuming from a preferred replica returned a long time ago, the client will never know of it *unless* the client periodically redirects back to the leader.
The Java client redirects back to the leader every MetadataMaxAge, but that seems a bit frequent (every 5min). This client defaults to 30min and adds a configuration option to raise or lower that.
A separate kfake integration test has been written and tested against this; it will remain in branch until the kgo 1.19 release (since currently, the kfake tests depend on released kgo versions).
Closes #905.

kgo: periodically redirect back to the leader & add config option

---

generate/gen.go
generate/main.go
pkg/kmsg/generated.go
pkg/kmsg/go.mod

Tags should only be encoded if they are not the default for their type. kmsg v1.11.0 introduced a tagged uuid field on FetchRequest, which is meant to be set only by brokers for inter-broker communication.
The uuid type previously did not have a defaulter in the generator, and the resulting generated code *always* encoded the ReplicaDirectorID field. If you upgraded kmsg and used it against an old Kafka, Kafka would fail to parse the request.
This commit now enforces that all tagged types have defaulters defined (the generator will panic if that is not the case), adds a defaulter for the uuid type, and fixes the generated code.
Closes #961.

generate: enforce all tags must have defaulters; kmsg: fix bug

---

pkg/kgo/metadata.go

We send an early metadata request ahead of the request-all-for-regex metadata request. The early request creates all topics by explicitly adding unknown produce topics into the request.
Test in a follow up PR in kfake (passing, but requires kgo release).
Closes #906.

kgo: fix AllowAutoTopicCreation && ConsumeRegex

---

generate/definitions/15_describe_groups
pkg/kmsg/generated.go

kmsg: properly annotate DescribeGroups.Group.ErrorMessage as v6+

---

pkg/kfake/18_api_versions.go
pkg/kgo/broker.go
pkg/kgo/producer.go

This can help reduce latency if you produce infrequently, but know you'll be producing shortly.
Closes #807.

kgo: add EnsureProduceConnectionIsOpen

---

pkg/kgo/errors.go

It is a smaller delta to expose a public func wrapping a private func than to make the private func public and change all usages of it.
I'm switching to Retryable rather than the currently exposed
kerr.Retriable or Broker.RetriableRequest. This is an inconsistency, but
Retryable feels more correct and what I've moved to for the past years:
https://english.stackexchange.com/a/305274
Closes #877.

kgo: expose IsRetryableBrokerErr

---

plugin/kprom/kprom.go

In Mimir we noticed that some metrics "disappeared" when we upgraded to `plugin/kprom/v1.2.0`. It looks like to be a regression introduced in https://github.com/twmb/franz-go/pull/936, where the `prometheus.Registerer` is removed from the config on the first call to `OnClientClosed()`. In this PR I propose to revert that change, preserving the behaviour we had in `v1.1.0` and before.
The `kprom` plugin implementation looks a bit weird to me. On one side it's a hook, and I would expect it to correctly work when used by multiple clients. In practice, it doesn't really work when it's used by multiple clients concurrently (e.g. `OnNewClient()` creates a new set of metrics each time and on each call to `OnClientClosed()` it removes all registered metrics, not just the ones that were created …

Fix regression introduced in plugin/kprom/v1.2.0 that causes the prometheus.Registerer to be removed from the config OnClientClosed()

---

pkg/kgo/consumer.go

To happen,
* A client must be consuming cooperatively and must be assigned new partitions after a rebalance
* The client must have just fetched offsets -- after which the client is internally in assignPartitions
* The client must have previously a running ListOffsets or OffsetForLeaderEpoch concurrently finishing (this is why we must be cooperatively consuming -- eager consumers kill everything in flight)
The second and third bullet points will concurrently try to update the map of using "cursors" (pointers in a partiiton).
The fix is to use an existing mutex -- the one already used by in list or epoch requests and responses -- in assignPartitions.
Closes #982.

kgo: fix data race in consumer code path

---

.golangci.yml
README.md
go.mod
pkg/kgo/broker.go
pkg/kgo/client.go
pkg/kgo/compression.go
pkg/kgo/compression_test.go
pkg/kgo/config.go
pkg/kgo/consumer_group.go
pkg/kgo/metrics_714.go
pkg/kgo/produce_request_test.go
pkg/kgo/sink.go

This supports 12 of the recommended 21 metrics; all 6 of the required ones.
KIP-1106 is supported by adding a client option, `UserMetricsFn`, allowing you to provide user metrics at every metric aggregation interval. Client metrics can be disabled with `DisableClientMetrics`. `UserMetricsFn` returns an `iter.Seq[Metric]`, requiring the minimum Go version for franz-go to be bumped to 1.23.
The compression API was simplified (hopefully) a bit by now not leaking an internal implementation detail.
This has been manually tested in two ways,
* Actual serialization was printed to a file and then validated with `protoc`.
This was done with:
```
git clone git@github.com:open-telemetry/opentelemetry-proto
protoc --proto_path=./opentelemetry-proto \
--decode …
```

KIP-714 & KIP-1106

---

README.md
pkg/kgo/client.go
pkg/kgo/config.go
pkg/kgo/consumer.go
pkg/kgo/consumer_direct.go
pkg/kgo/consumer_group.go

ConsumeResetOffset has always been confusing when trying to figure out what exactly it does and when. The main point of confusion (for me) has always been trying to reason about where I want to start consuming new partitions vs. where to reset to when a problem is encountered.
Well, we can split the two into dedicated options to resolve the confusion.
This also hopefully cleans up and clarifies which offset is used when. As it turns out, there really is only one place where the reset offset is used, and it's used very rarely (a niche sub-case of when OffsetOutOfRange is encountered). It's likely best to just leave it as NewOffset().AtStart().
I've read through KIP-1106 a few times, and given that the client already tries to reset to the best offset (right after the last succesfully …

kgo: add ConsumeStartOffset, expand offset docs, update readme KIPs

---

pkg/kgo/client.go
pkg/kgo/consumer_group.go

ApiVersions can succeed even if the broker requires SASL and you forgot it in the client. Metadata forces a full SASL flow.

kgo: switch Ping to issue a broker-only metadata request

---

examples/hooks_and_logging/expansive_prometheus/metrics.go

The topic was incorrectly being added to the partition section. And the partition is actually the node id

Typo in Hooks Example

---

pkg/kgo/broker.go
pkg/kgo/hooks.go

This allows end users to detect any sasl errors via OnBrokerConnect.
This does mean the metric will look higher; if that's unacceptable after release, this commit can be reverted and a different hook that differentiates dialDur vs initDur can be introduced.
Closes #1003.

kgo: change OnBrokerConnect to encompass the whole connect initialization flow

---

pkg/sr/client.go
pkg/sr/clientopt.go
pkg/sr/clientopt_test.go

This PR refactors the `DialTLSConfig` option setter so the TLS config is stored in `sr.Client` and applied in `sr.NewClient` instead of the option setter.
Note that using `DialTLSConfig()` overrides any client set with `HTTPClient()`. This is the same behaviour as before.
After this PR is merged, I will add the missing `OptValues` case for the `DialTLSConfig` option to #963.
Fixes #971

sr: refactor DialTLSConfig option so it is stored in client

---

.github/workflows/lint-and-test.yml
pkg/kgo/broker.go
pkg/kgo/client_test.go

This fixes a bug that has existed in this codebase forever, and only now finally can occur.
In Kafka 2.4, Kafka introduced KIP-511, bumping ApiVersion to v3.
I misread the KIP and assumed that the broker would send ALL API keys when the broker did not understand the version of the ApiVersions request we were sending.
In franz-go, if the client detects an UNSUPPORTED_VERSION error,
* Brokers pre 2.4 would outright send nothing; we would downgrade our request to v0 and retry. This worked.
* Brokers post 2.4, I deserialized the response as v0 and assumed I had all keys.
As it turns out, the broker returns only _one_ key, which is the version of ApiVersions that the broker supports. This would allow the client to re-request ApiVersions with the highest version the broker supports.
This was …

kgo bugfix: ApiVersions replies only with key 18, not all keys

---

pkg/kgo/logger.go
pkg/sr/client.go
pkg/sr/clientopt.go
pkg/sr/logger.go

It includes 3 new client options to set the
logger function and the logger level.
It mirrors kgo's Logger and LogLevel definitions,
making it easy to use any existing kgo logging
functionality you may already be using in this
package as well.

sr: Add logger function to schema registry client

---

generate/main.go
pkg/kmsg/internal/kbin/primitives.go
plugin/kprom/config.go

I note that go generate ./... fails with latest gofumpt
```console
$ go generate ./...
panic: invalid Go version: "1.19"
goroutine 18 [running]:
mvdan.cc/gofumpt/format.File(0xc000012080, 0xc0001920a0, {{0x7ffe3a2a4da4, 0x4}, {0x0, 0x0}, 0x1})
/home/tiago/work/go/pkg/mod/mvdan.cc/gofumpt@v0.8.0/format/format.go:99 +0x27c
main.processFile({0x63bbc5, 0x10}, {0x0, 0x0}, {0x68a398?, 0xc000186028?}, 0xc0001962b0, 0x1)
/home/tiago/work/go/pkg/mod/mvdan.cc/gofumpt@v0.8.0/gofmt.go:327 +0x38d
main.gofmtMain.func2(0x0?)
/home/tiago/work/go/pkg/mod/mvdan.cc/gofumpt@v0.8.0/gofmt.go:508 +0x3a
main.(*sequencer).Add.func2()
/home/tiago/work/go/pkg/mod/mvdan.cc/gofumpt@v0.8.0/gofmt.go:191 +0x42
created by main.(*sequencer).Add in goroutine 1
/home/tiago/work/go/pkg/mod/mvdan.cc/gofumpt@v0.8.0/gofmt.go:190 …
```

Fix go generate

---

pkg/kadm/go.mod
pkg/kadm/go.sum
pkg/kadm/groups.go
pkg/kadm/kadm.go

If a group is actively rebalancing or cooperative but rebalancing for the first time, the group will not have assigned partitions. We can look at what each member WANTS to consume and use that as further input into lag calculations.
This adds a few helper APIs to make further lag calculation easy (JoinTopics alongside AssignedPartitions, and a MergeTopics API on TopicsSet).
When iterating over all members, after we iterate over their assigned partitions, we can iterate over their interested topics and prime the lag map. If the topic is not in the lag map, add it. The existing logic at the end of the function goes over all topics in the lag map and calcuates lag per partition for all missing partitions.

kadm: bump deps, new APIs to support better lag

---

.golangci.yml
pkg/kgo/client.go
pkg/kgo/client_test.go
pkg/kgo/internal/sticky/sticky_test.go
pkg/kgo/sink.go
pkg/kgo/source.go
pkg/kversion/requests.go

Copying the second commit,
All credit to @douglasbouttell for the excellent find here.
Batched FindCoordinator requests against brokers that do not support
batched requests no longer worked at of 1.19.3. The problem was the
removal of pinReq, and well, a bug in the full removal.
This fixes the problem and adds a test test that fails without the fix.
I checked all linters I know of (opting into all revive, staticcheck,
gocritic, golangci-lint linters) and none of them catch this, for valid
reasons. It's hard to check.
I then went back and forth with Claude to generate some code that would
check it, and surprisingly came up with something. However, since it
generates a _few_ false positives and I don't want to learn enough of
the ast code to fully maintain the linter, I'm going to comment …

Fix misused variable from 1.19.3's pinReq removal

---

pkg/kfake/groups.go
pkg/kfake/issues_test.go

Ensure consumer group goroutines exit after the cluster is closed.
Also, ensure clients are closed in all tests.
Closes https://github.com/twmb/franz-go/issues/1037

pkg/kfake: exit group managers on cluster shutdown

---

pkg/sr/client.go
pkg/sr/client_test.go

This PR fixes a crash in `Client.OptValues` when no basic auth is configured (see linked issue for details).
Summary of changes:
* fixes segfault when no basic auth is configured
* also implement testing of default client values in TestOptValue
* also move testing of OptValues to own TestOptValues test
Fixes #1043

sr: check for nil for basicAuth in Client.OptValues

---

plugin/kprom/kprom.go

I noticed `buffered_fetch_bytes_total` and `buffered_produce_bytes_total` were not exported by the kprom metrics plugin so I've added them in this PR.
The [kvictoria](https://github.com/twmb/franz-go/blob/master/plugin/kvictoria/kvictoria.go#L126-L128) plugin already exports these metrics.  However, I noticed these metrics are not exported by kotel and kgmetrics and I'm not sure whether they should be or not.  
In any case, I think adding these metrics to kprom would be really useful so I decided to start with that.  Thanks!

Add buffered fetch/produce bytes to prometheus metrics

---

pkg/sr/client.go

This allows users to extend the client for non-standard schema registry endpoints while reusing the client's configuration.

sr: expose client.Do method

---

pkg/kadm/groups.go

Hello! First of all, I want to say that I really appreciate your brilliant work! 🙏
We've got a panic using Lag function and I decided to investigate the reason.
DescribeGroups makes ListGroups request if there was no groups passed explicitly. We can get errors from ListGroups and in that case this code will panic.
I'm not sure wether this code is absolutely correct because we simply skip errors and nobody will be aware about some possibly skipped groups.

Panic fix in kadm.Lag function

---

.github/workflows/lint-and-test.yml
pkg/sr/client_test.go

PR #1060 broke the testing suite in the `sr` package:
```
./client_test.go:373:43: invalid operation: v.(Param) == Param{} (struct containing url.Values cannot be compared)
FAIL    github.com/twmb/franz-go/pkg/sr [build failed]
FAIL
```
This PR fixes the testing suite after the recent addition of `rawParams` to `Param`.
EDIT: I added a GA workflow now to also run tests for the `sr` package. This should help detect future breakage.

sr: fix unit testing after recent `Param.rawParams` addition

---

pkg/sr/api.go
pkg/sr/client_test.go

First of all, apologies for submitting a PR with a new feature without starting a discussion about it first.
I thought this feature is simple enough and justified to just submit it for inclusion.
We recently migrated our Kafka cluster from Confluent 6.2.x to 7.8.x. In our setup, we have the ACL authorizer plugin configured in the Schema Registry service for implementing security. Until version 6.2.x, the `sr` package worked like a charm, however in version 7.8.x we hit access denied issues without any code changes.
After deeper investigation, we discovered that the new Schema Registry version does not apply ACL authorization correctly for the `GET /schemas/ids/{id}/versions` endpoint. Therefore, when calling `Client.CreateSchema`, we get 403 errors when the function tries to obtain the …

sr: add new `Client.RegisterSchema` function

---

examples/bench/compare/segment/go.mod
examples/bench/compare/segment/go.sum
examples/bench/compare/segment/main.go

Before:
```
go run . -topic foo -compression=snappy
0.42 MiB/s; 4.42k records/s
0.43 MiB/s; 4.51k records/s
0.43 MiB/s; 4.47k records/s
0.44 MiB/s; 4.60k records/s
0.46 MiB/s; 4.81k records/s
0.40 MiB/s; 4.24k records/s
0.47 MiB/s; 4.88k records/s
0.44 MiB/s; 4.65k records/s
```
After:
```
go run . -topic foo -compression=snappy
151.22 MiB/s; 1585.65k records/s
169.11 MiB/s; 1773.20k records/s
168.29 MiB/s; 1764.67k records/s
173.17 MiB/s; 1815.83k records/s
171.54 MiB/s; 1798.78k records/s
169.92 MiB/s; 1781.72k records/s
161.79 MiB/s; 1696.47k records/s
158.54 MiB/s; 1662.38k records/s
166.67 MiB/s; 1747.62k records/s
160.80 MiB/s; 1686.13k records/s
167.65 MiB/s; 1757.96k records/s
```
For some reason this is still slower than https://github.com/twmb/franz-go/pull/1064 by about …

chore: optimize segment producing

---

pkg/sr/client.go
pkg/sr/errors.go
pkg/sr/srfake/errors.go
pkg/sr/srfake/handlers.go
pkg/sr/srfake/http.go
pkg/sr/srfake/registry.go

- Add comprehensive error code constants from official Confluent Schema Registry
- Include helper functions for error categorization
- Update srfake package to use centralized constants
- New pkg/sr/errors.go with all 24 official error codes
- Helper functions: IsNotFoundError(), IsInvalidRequestError(), IsServerError()
- Remove duplicate constants from srfake package
- Maintains backward compatibility

feat: add Schema Registry error code constants

---

pkg/kgo/metadata.go

Scenario is:
* cluster returns topic ID on metadata update 1
* cluster does not return topic ID on metadata update 2
* metadata update 3 causes a panic
By not copying the old topic partition data into the new pointer, the new pointer is seen as a new partition -- and almost all fields were not initialized. So, the third update is now updating a partially initialized cursor. The `cursorsIdx` field is -1 on initialization (which is the bug, since we did not copy the old index), and we panic when trying to remove that index from the cursors slice.
This is only possible against a cluster that does not properly handle topic IDs; in particular, this bug has existed since 2023 and has never been encountered. This popped up against a broker implementation that also has a followup to fix here.

kgo: fix panic in metadata updates from inconsistent broker state

---

generate/definitions/01_fetch
pkg/kgo/source.go
pkg/kmsg/generated.go

* Incorrect doc line in generate/definitions (&& regenerate kmsg from this)
* Accidental c&p error on doc line in kgo (not sure how a linter didn't catch this)

repo: fix two typos

---

examples/goroutine_per_partition_consuming/autocommit_marks/main.go
examples/goroutine_per_partition_consuming/manual_commit/main.go

fixed typo in group consuming examples

---

pkg/kgo/config.go

pull request for #1095 
Set lower limit for request timeout overhead to 100ms

#1095: alter 'request timeout overhead'; set minimum to 100ms

---

pkg/kgo/broker.go
pkg/kgo/connreset_unix.go
pkg/kgo/connreset_windows.go

The connection reset error message is not the same across operating systems, so instead check if it's a net.Error.
Fixes #1102

kgo: make connection reset error check portable

---

.github/workflows/lint-and-test.yml
examples/bench/go.mod
examples/bench/main.go
pkg/kgo/config.go
pkg/kgo/producer.go
pkg/kgo/sink.go
pkg/kgo/topics_and_partitions.go

* Fixes multiple linger bugs that caused linger timers to fire more than they should
* Fixes backwards conditional determining if more records existed to drain (no impact previously because draining was triggered in many other ways)
* Adds a few flags to the bench utility

Minor fixes / internal improvements
