twmb/franz-go

pkg/kgo/consumer_group.go

Log missing error if auto commit errors.

Consumer group autocommit log error

---

plugin/kzap/README.md

Capitalize Uber in kzap README so that I appear as contributor

Capitalize Uber in kzap README

---

plugin/kprom/kprom.go

Use Registerer and Gatherer interface instead of concreate Registry type
This allows the user of the plugin to:
- pass prometheus.DefaultRegisterer and prometheus.Defaultgatherer
- pass a testing a custom Registerer implementation (e.g. for testing purposes)
The change is backwards compatible.

kprom: use Registerer and Gatherer interface instead of concreate Registry type

---

pkg/kgo/client.go
pkg/kgo/client_test.go

Closes https://github.com/twmb/franz-go/issues/59

client: fix broker address parsing

---

pkg/kgo/consumer_group.go

Signed-off-by: Vasiliy Tolstov <v.tolstov@unistack.org>

when CommitRecords commit next offset to move forward

---

pkg/kgo/consumer_group.go

Signed-off-by: Vasiliy Tolstov <v.tolstov@unistack.org>

add locking to g.uncommitted MarkCommitRecords

---

plugin/kprom/README.md

Signed-off-by: Ladislav Macoun <ladislavmacoun@gmail.com>

kprom: fix typo in example

---

plugin/kprom/kprom.go

https://github.com/twmb/franz-go/issues/179

Add a link to the prometheus examples to the godoc

---

pkg/kadm/topics.go

fixes #235 
Took a quick look through the rest of the kadm things and it seems like this was the only one missing the appends.

append partitions and topics to delete records request

---

pkg/kgo/consumer_group.go

We clear nowAssigned at the end of a group session, meaning using it for our prior assignment is invalid and would always be empty. Thus, we would never preserve stickiness.
Now, we use our lastAssigned for stickiness, we *always* set it, and we set it after using the current/prior values and before we clear nowAssigned.

{Cooperative,Sticky}Balancer: bug fix lack of stickiness

---

pkg/kgo/compression.go

Fix missing codecType

---

generate/definitions/23_offset_for_leader_epoch
generate/definitions/misc
pkg/kmsg/generated.go

For #272, we need to tag the kmsg protocol first.

kmsg: commit new ConsumerMemberMetadata for KIP-792

---

generate/definitions/misc
pkg/kmsg/generated.go

PR is open and this is leaning to be merged committing now so I can tag kmsg and use it in #272.

kmsg: commit new proto for KIP-881

---

pkg/kgo/client.go

If we are repeatedly unable to dial the controller or coordinator, it is possible that the broker is just gone. We need to clear our cache internally so that we refresh the cache and pick up a new controller / coordinator.
We retry 3 times just to handle temporary dial errors.
Closes #239.

kgo: clear controller/coordinator caches on failed dials

---

README.md

Added Unity to the Who uses this section of the readme

Updated who uses this

---

generate/definitions/62_broker_registration
pkg/kmsg/generated.go
pkg/kversion/kversion.go

From 67c72596afe58363eceeb32084c5c04637a33831
Thankfully, kmsg has not been tagged with this change yet.

generate: fixup KIP-866 changes

---

examples/admin_client/README.md
examples/admin_client/go.mod
examples/admin_client/main.go
pkg/kadm/topics.go

Add create topic admin function

---

README.md
generate/gen.go
generate/main.go
generate/parse.go
pkg/kmsg/internal/kbin/primitives.go

Tested on SnapshotID. This will be further tested once KIP-848 is implemented.

generate: support KIP-893

---

pkg/kversion/kversion.go

Tested with kcl, we can now probe 3.4 successfully.
This required a bit of a change to version guessing (and I really hope KIP-885 is in by the next release...). Previously, we would skip the few internal APIs by default. Now, if the ApiVersion response includes an API we are skipping, we check it.

kversion: cut Kafka 3.4

---

README.md
go.mod
go.sum
pkg/kgo/group_balancer.go
pkg/kgo/internal/sticky/sticky.go

This improves problems in the face of re-joining consumer zombies.

group balancer: support KIP-792

---

pkg/kgo/consumer_direct_test.go

Per the other tests. Kafka is problematic sometimes.

kgo testing: have unlimited retries when producing to new topic

---

pkg/kgo/client.go
pkg/kgo/source.go

We allow 1s to send a final empty fetch request indicating that the fetch session should be closed.
This also fixes the previous direct-consumer path that allowed consuming to continue while the client was shutting down, which could potentially result in a spurious context.Canceled rather than ErrClientClosed error.
Closes #349.

consuming: close fetch sessions when closing the client

---

pkg/kadm/configs.go

kadm: add state config altering using the older AlterConfigs request

---

pkg/kadm/topics.go

kadm: add NumPartitions,ReplicationFactor,Configs to CreateTopicResponse

---

plugin/kotel/tracer.go

plugin/kotel.Tracer: add KeyFormatter, only accept utf8 keys

---

.golangci.yml
CHANGELOG.md
README.md
pkg/kgo/producer.go

producer: avoid deadlock when when quickly recreating a topic

---

pkg/kfake/cluster.go

This permits tests using kfake to simulate the
movement of a partition leader from one broker to
another.

kfake: simulate rebalancing of partitions

---

pkg/kgo/config.go
pkg/kgo/consumer_group.go
pkg/kgo/txn.go

See comments. This is also a different and arguably better approach to the old issue #137.
Closes #409.
Closes #137.

kgo groups: block join&sync while a commit is inflight

---

pkg/kfake/08_offset_commit.go
pkg/kfake/09_offset_fetch.go
pkg/kfake/10_find_coordinator.go
pkg/kfake/11_join_group.go
pkg/kfake/12_heartbeat.go
pkg/kfake/13_leave_group.go
pkg/kfake/14_sync_group.go
pkg/kfake/15_describe_groups.go
pkg/kfake/16_list_groups.go
pkg/kfake/23_offset_for_leader_epoch.go
pkg/kfake/42_delete_groups.go
pkg/kfake/NOTES
pkg/kfake/client_conn.go
pkg/kfake/cluster.go
pkg/kfake/config.go
pkg/kfake/groups.go
pkg/kfake/misc.go

This passes franz-go's TestGroupETL/ suite

kfake: add support for groups

---

pkg/kgo/consumer.go

See comment; this is a little bit confusing to explain though.

kgo consumer: do not use the partition epoch when assigning offsets

---

pkg/kgo/client.go

Technically, a request that goes to the sharding logic that is pinned to a minimum version that fails due to errBrokerTooOld has never been issued. Currently, if a request is enqueued for a long time due to the client being throttled, it can fail with errBrokerTooOld even though it was never issued.
Instead, if the request is pinned and the error is errBrokerTooOld, we always retry immediately (up to 3 times, for safety).

kgo: avoid counting pinReq version failures against retries

---

pkg/kgo/client.go

See embedded comment;
This improves ListOffsets, OffsetForLeaderEpoch, and a few other random requests.

client: always retry on NotLeader for sharded requests

---

README.md

I felt it would look inconsistent to put emojis in the list itself so I'll add them here: ❤️🫦

Add Benthos to the README users list

---

pkg/sr/api.go
pkg/sr/client.go
pkg/sr/config.go
pkg/sr/serde.go

* cancel contexts
* fix comments
* remove unused field in Client
* relax expected response code
* relax parsing of error response to accept non-json body
* fix setting the mode

Schema registry fixes

---

docs/producing-and-consuming.md

change SessionTimeout to RebalanceTimeout.
discussed in: https://github.com/twmb/franz-go/issues/471

Fix consumer docs

---

pkg/kfake/cluster.go

In order to preserve the existing API, we add a `RequestNodeId`, valid only during a control function, which returns the node id of the broker that the current request was attached to.

kfake: Expose the current broker's node ID during request interception

---

pkg/kgo/config.go

Trivial fix 🙃 Sorry for the noise, couldn't resist.

pkg/kgo/config.go: fix typo

---

pkg/kfake/00_produce.go
pkg/kfake/03_metadata.go
pkg/kfake/19_create_topics.go
pkg/kfake/21_delete_records.go
pkg/kfake/32_describe_configs.go
pkg/kfake/33_alter_configs.go
pkg/kfake/34_alter_replica_log_dirs.go
pkg/kfake/35_describe_log_dirs.go
pkg/kfake/44_incremental_alter_configs.go
pkg/kfake/47_offset_delete.go
pkg/kfake/NOTES
pkg/kfake/cluster.go
pkg/kfake/data.go
pkg/kfake/data_test.go
pkg/kfake/groups.go
pkg/kfake/topic_partition.go

* DeleteRecords
* DescribeConfigs
* AlterConfigs
* IncrementalAlterConfigs
* OffsetDelete
* DescribeLogDirs
* AlterReplicaLogDirs

kfake: support 7 more requests

---

pkg/kadm/metadata.go

Discovered while looking into a bug in kfake; even if the broker is bugged, kadm should not panic.

kadm: do not trust non-nullable topics

---

pkg/kgo/consumer.go
pkg/kgo/consumer_group.go
pkg/kgo/group_balancer.go
pkg/kgo/group_balancer_test.go

Fixes two bugs from v1.14, and adds a fix for an old not-quite-bug,-but-not-quite-correct

v1.14 patches

---

pkg/kfake/cluster.go

If a control function calls KeepControl, or Control/ControlKey for that matter, then it will append to the control function slice. When tryControl removes the control function, it is referencing a possibly stale slice. Refresh the slice before removing the element.

pkg/kfake: fix KeepControl

---

pkg/kgo/metadata.go
pkg/kgo/source.go

When using a fetch session, if we stop fetching a topic or partition, we send that information in the fetch request.
If we forget an entire topic, that means we do not add any cursor for the topic internally -- we just outright are no longer fetching the topic -- we previously had no topic ID in the fetch request for the forgotten topic. When sending this forgotten topic in the fetch request, we would not have the ID for it, and this would cause a NPE in Kafka.
Now, when we add a topic to the session, we also save the topic ID. We use this for two purposes:
* Now we correctly send the forgotten topic ID
* We also can pin fetch requests to non-topic-ID versions if any topic is missing an ID at any point in the session (i.e. if a forgotten topic has no ID)
Lastly we add a guard in metadata …

kgo: track topic IDs in the fetch session

---

pkg/kadm/groups.go

kadm: change FetchOffsetsForTopics to only return requested topics by default

---

pkg/kgo/client.go
pkg/kgo/config.go

kgo: expose ConsiderMissingTopicDeletedAfter

---

pkg/kgo/consumer.go

kgo: add NewErrFetch

---

pkg/kadm/groups.go

If listing end offsets errored, then the lag would have no topic/partition. We now add Topic and Partition to the Lag itself so that we can always ensure we set these fields to be non-empty (and this makes it easier to reason about what field to use if you use groupLags.Sorted()).

kadm: fix occasionally empty topic/partitions in Lag

---

pkg/kgo/source.go

Adding topics to a session needs to use the fetch request's topic2id map (which then promotes IDs into the session t2id map).
Importantly, and previously this was wrong / not the case: removing topics from a session needs to use the session's t2id map. The topic does not exist in the request's topic2id map, because well, it's being forgotten. It's not in the fetch request.
Adds some massive comments explaining the situation.
Closes #620.

kgo source: use the proper topic-to-id map when forgetting topics

---

pkg/kadm/groups.go
pkg/kadm/partas.go
pkg/kadm/topics.go

Adds Error for many responses, which may sometimes be helpful.

kadm: add DeleteTopic,DeleteGroup,Error

---

README.md

At Hilton we use `franz-go` with `kafka` for eventing within our `go` micro-services.

Update `README.md` to add `Hilton` as a user

---

examples/transactions/eos/main.go

eos example: avoid short-circuit logic

---

pkg/kadm/kadm.go

This adds `NewOffsetFromRecord` function that may be helpful for manually committing offsets

kadm: add `NewOffsetFromRecord` helper function

---

pkg/sr/client.go

sr: add StatusCode to ResponseError, and message if the body is empty

---

pkg/sr/api.go

Note: This is a breaking change, but I guess the impact is minimal.

Specify the type for `sr.SoftDelete` and `sr.HardDelete`

---

pkg/kfake/cluster.go

kfake: do not listen until the cluster is fully set up

---

pkg/kgo/consumer.go
pkg/kgo/source.go

See embedded comments.
Closes #885.

kgo: redirect back to the leader on KIP-392 case 3 failure

---

pkg/kadm/go.mod
pkg/kadm/go.sum

Just to have a slightly different tag; this commit is inconsequential.

kadm: bump dep

---

pkg/kadm/metadata.go
pkg/kadm/topics.go

Based on the conversation here: https://github.com/twmb/franz-go/issues/925

Disable metadata fetch of authorized operations by default

---

plugin/kprom/config.go
plugin/kprom/kprom.go

https://github.com/twmb/franz-go/issues/926

added static label

---

pkg/kfake/37_create_partitions.go
pkg/kfake/data.go
pkg/kfake/topic_partition.go

kfake: add TopicIDInfo to complement TopicInfo, but when you have an ID

---

pkg/kmsg/generated.go

I have no clue how the generated code was incorrect in the merged branch.

kmsg: commit actually correct generated code

---

pkg/kgo/client.go
pkg/kgo/config.go
pkg/kgo/producer.go

kgo: add DefaultProduceTopicAlways ProducerOpt

---

plugin/kotel/tracer.go

Feature for #940
Creating a link to the produce span rather than a direct child relationship.

kotel: consumer span links

---

plugin/kprom/config.go
plugin/kprom/kprom.go

Fixes https://github.com/twmb/franz-go/issues/914

feat: collector pattern for kprom

---

pkg/kadm/groups.go

Previously, non-empty groups would only consider actively assigned partitions as eligible for lag calculations. If a topic was previously consumed by a group but is no longer assigned, it would not show up as lagging. Conversely, empty groups considered all partitions previously committed to (_and_ all partitions not committed to in topics where *other* partitions are committed to) as eligible for lag.
This commit unifies the logic.
Closes #902.

kadm Lag: have consistent logic for empty and non-empty groups

---

pkg/kgo/consumer.go
pkg/kgo/errors.go

kgo: expand ErrDataLoss with the epoch before & after

---

go.mod
pkg/kadm/go.mod
pkg/kfake/go.mod
pkg/kmsg/go.mod
pkg/sasl/kerberos/go.mod
pkg/sr/go.mod
plugin/kgmetrics/go.mod
plugin/klogr/go.mod
plugin/klogrus/go.mod
plugin/kotel/go.mod
plugin/kphuslog/go.mod
plugin/kprom/go.mod
plugin/kslog/go.mod
plugin/kvictoria/go.mod
plugin/kzap/go.mod
plugin/kzerolog/go.mod

No toolchain preference here besides the min version.

all: remove toolchain lines

---

pkg/kadm/metadata.go
pkg/kfake/02_list_offsets.go
pkg/kfake/data.go
pkg/kfake/go.mod
pkg/kfake/go.sum
pkg/kfake/issues_test.go

- **list_offsets: timequeries are inclusive**
- **kfake: add a test for ListOffsetsAtOrAfterMilli**

Fix timequeries to be inclusive

---

pkg/sr/client.go
pkg/sr/client_test.go

This PR adds `Client:OptValue` and `Client.OptValues` functions to the `sr` package.
These are heavily based on the functions of the same name in the `kgo` package.
~~Note that I did not add a case and unit test for the `DialTLSConfig` option because this option creates a new `http.Client` object with TLS preconfigured instead of storing the TLS config in the client struct.~~ EDIT: Added now after merged #978.
Fixes #954

sr: add `Client.OptValue` and `Client.OptValues` functions

---

pkg/kfake/00_produce.go
pkg/kfake/01_fetch.go
pkg/kfake/02_list_offsets.go
pkg/kfake/03_metadata.go
pkg/kfake/08_offset_commit.go
pkg/kfake/09_offset_fetch.go
pkg/kfake/10_find_coordinator.go
pkg/kfake/15_describe_groups.go
pkg/kfake/16_list_groups.go
pkg/kfake/go.mod
pkg/kfake/go.sum
pkg/kfake/groups.go

* update all requests to latest kafka 4 stuff -- most have no new behavior (for only the supported requests!)
* bump deps
Closes #968

kfake: updates

---

examples/dlq/README.md
examples/dlq/go.mod
examples/dlq/go.sum
examples/dlq/main.go
examples/mark_offsets/README.md
examples/mark_offsets/go.mod
examples/mark_offsets/go.sum
examples/mark_offsets/main.go

some examples of commiting mark offsets and consuming with DLQ mechanism

kgo: add examples of commiting mark offsets and consuming with dlq
